### ISSUE TITLE
M3U8不能播放

### ISSUE THREAD

**Issue by Millertoken** [ashqal/MD360Player4Android#1]
@ashqal 
你好。看到你的这个DEMO非常开心。正好需要这个功能。感谢你的无私分享。
在你的DEMO里面遇到一个问题，DEMO提供的M3U8地址有声音，画面出不来。替换了其他M3U8地址也有同样的情况。换成MP4的地址则无这个问题。请问下，这是什么原因呢？
另外，每次在把手控制画面改成陀螺仪的时候，都会出现滑动转动很多圈的情况。试了一下，发现是陀螺仪的问题。当快速转圈的时候，陀螺仪会出现回滚的情况。

**Comment by ashqal** [comment]
1.这个库只关注渲染，M3U8播放问题似乎应该归结于MediaPlayer，不在讨论之列，你可以试试用MediaPlayer播放M3U8能不能播放出来
2.转很多圈的问题可以提供下机型吗？我的魅族MX3也有这个问题，我的new moto g偶尔会有问题

**Comment by Millertoken** [comment]
@ashqal 
M3U8的问题我换了一个player可以了。
转圈的机型是三星盖世5。我的陀螺仪是正常的，其他应用是OK的呢。

**Comment by Millertoken** [comment]
@ashqal 另外，是否应该使用陀螺仪来控制移动的角度。我看你好像使用的旋转的传感器

**Comment by ashqal** [comment]
陀螺仪出来的数据是加速度，无法表现现有的旋转角度，所以使用的是旋转矢量感应器，这方面参考了[PanframeSDK](http://www.panframe.com/)

**Comment by ZhengzhongSun** [comment]
Panframe的sdk并没有开源吧，想问下您是怎么参考的？再就是关于这个program的原理，有地方可以详细介绍下吗？

**Comment by ashqal** [comment]
1、Panframe是纯java的项目，可以看混淆过的代码
2、搜一下opengles program，资料应该还蛮多的

**Comment by ZhengzhongSun** [comment]
1、您指的是反编译吗？您有反编译好的代码能发我份吗？459642390@qq.com 谢了！
2、我指的是您做这个的原理，是找到像平面像素点与球心每一跟光线的theta和phi，然后在全景图中找对应像素吗？

**Comment by ashqal** [comment]
1、把jar引进去，as里直接可以看
2、原理其实很简单，android支持`uniform samplerExternalOES`类型的texture，使用android自带的`android.graphics.SurfaceTexture#updateTexImage`方法，就可以把视频作为一个Texture贴给一个球面

**Comment by ZhengzhongSun** [comment]
1、我把jar引进去，只能看到他的一些函数名，里面的实现都看不到
2、有直接的函数可以直接将全景图贴到球的的内表面？

**Comment by ashqal** [comment]
1、可以看到，as里展开那个jar就可以看到了
2、视频、图片我都做了实现，[MD360VideoTexture.java](https://github.com/ashqal/MD360Player4Android/blob/master/vrlib/src/main/java/com/asha/vrlib/texture/MD360VideoTexture.java)，[MD360BitmapTexture.java](https://github.com/ashqal/MD360Player4Android/blob/master/vrlib/src/main/java/com/asha/vrlib/texture/MD360BitmapTexture.java)

**Comment by ZhengzhongSun** [comment]
1、PFView PFAsset 里面都没有源码，但有一些命名为a b c d e f g....的文件是源码？这些文件没有功能说明，应该怎么看呢？
2、谢谢，我好好看下

**Comment by ashqal** [comment]
Demo中已使用`IjkMediaPlayer`作为播放器
