### ISSUE TITLE
全景切换3d 溢出(director list ArrayIndexOutofBoundsException)

### ISSUE THREAD

**Issue by DeloDuan** [ashqal/MD360Player4Android#100]
![image](https://cloud.githubusercontent.com/assets/6212937/17800980/ea46628c-6619-11e6-898a-1ac2c8f29cd5.png)

**Comment by reaper12** [comment]
+1 出现过一次

**Comment by ashqal** [comment]
f94211b1cfe1b20b9842fb95e6da5a11af2f019a
应该解决了，创建了MDGLHandler去处理GL线程和主线程之间的线程同步造成的crash问题
