### ISSUE TITLE
How to get center location of every frame?

### ISSUE THREAD

**Issue by yenchenlin** [ashqal/MD360Player4Android#104]
Hello, is there any way to get center view location per frame if I defined the coordinate system as follow?

![unnamed](https://cloud.githubusercontent.com/assets/7057863/17975679/38b5c02c-6b1d-11e6-86dc-171365fce15f.png)

**Comment by yenchenlin** [comment]
I've read #37 but `mModelMatrix` now seems to be commented out.

**Comment by ashqal** [comment]
This coordinate system is not supported now, but
Touch Picker
![image](https://cloud.githubusercontent.com/assets/5126517/17994499/ce8b6354-6b8b-11e6-86f0-d05ddf061078.png)

Eye Picker
![image](https://cloud.githubusercontent.com/assets/5126517/17994513/eab1f0ac-6b8b-11e6-9402-a31614bd7424.png)

**Comment by yenchenlin** [comment]
Thanks @ashqal , 那有辦法在播放 video 的每個時間點都得到 `MDRay` 嗎？

**Comment by ashqal** [comment]
@yenchenlin Eye Picker will do hit test onDrawFrame, if there is any hotspot hit, `onHotspotHit` will be callback.

**Comment by yenchenlin** [comment]
那我有辦法把整個 3d 球都設定成 `hotspot` 嗎？

**Comment by yenchenlin** [comment]
@ashqal I finally achieved my goal by adding a **hidden** plugin to access Ray every moments.

Again, thanks for your great patience and nice work! 😄

**Comment by mudin3i** [comment]
Hello,

@yenchenlin Could you share some source code for hint? 
I also need what you have done. But i am new in android development. I cannot figure it out
Thanks. 

Best regards,

Mudin
