### ISSUE TITLE
I need you help

### ISSUE THREAD

**Issue by obraz** [ashqal/MD360Player4Android#107]
Hi. You have created awesome library ))
I want to know is it possible to set starting default video view position? I mean when I keep device vertical always opening video in one zero point. Like in this app
https://play.google.com/store/apps/details?id=com.littlstar.android

Thanks

**Comment by leo-plus** [comment]
I don’t understand your problem clearly. But maybe I had the same issue and I just solved it. 

Try use sensor TYPE_GAME_ROTATION_VECTOR.

Though you can set up you camera with some Matrix in MD360player with OpenGL API, but when you use your sensor, your camera's orientation will affected by the Matrix which the sensor give.  

In the MD360player, it used sensor  TYPE_ROTATION_VECTOR which coordinate is base off magnetic, so it's always point some magnetic orientation, not your device Z axis orientation when the view created.

**Comment by obraz** [comment]
Excellent. TYPE_GAME_ROTATION_VECTOR it's just what I need. Can you make this parameter customizable?

**Comment by leo-plus** [comment]
Well... That depends on the author @ashqal

**Comment by obraz** [comment]
Another problem - video always starts from last position. But I need that the video always starts from one position

**Comment by leo-plus** [comment]
I don't know and I suggest u to open other issue to talk about this.
