### ISSUE TITLE
横竖屏切换后显示和控制都不对

### ISSUE THREAD

**Issue by liuyinchang** [ashqal/MD360Player4Android#109]
横竖屏切换使用onConfigurationChanged，但是切换以后图片显示和控制都不正确了，请问下应该怎么处理横竖屏切换的问题。谢谢

**Comment by hike2008** [comment]
我遇到竖屏模式下, 画面旋转 90度的情况;

**Comment by zengxin** [comment]
我也遇到了，貌似一转屏就出问题。显示出现90度误差，控制也是一样。怎么解决呢？谢谢

**Comment by ashqal** [comment]
是个bug，motion模式切换方向后应该重新获取下当前的方向，切换到touch再切换回motion问题可以解决

**Comment by ashqal** [comment]
``` java
dependencies {
    compile 'com.github.ashqal:MD360Player4Android:a83b2d0c2f'
}
```
