### ISSUE TITLE
Video failed to load when tried with a video other than the sample video in this project from my server.

### ISSUE THREAD

**Issue by Eldho93** [ashqal/MD360Player4Android#11]
@ashqal : Very helpful library indeed. But I tried to load a video from my server and the player failed to play it..

**Comment by ashqal** [comment]
Please ensure that the video can be played by `android.media.MediaPlayer` directly.

**Comment by Eldho93** [comment]
Is there anything special step in uploading the video to the server? Like
the format of the video,or anything like that?

On Thu, Apr 21, 2016 at 3:45 PM, Asha notifications@github.com wrote:

> Please ensure that the video can be played by android.media.MediaPlayer
> directly.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ashqal/MD360Player4Android/issues/11#issuecomment-212843848

## 

Yours SIncerely,
Eldhose Paul

**Comment by Eldho93** [comment]
@ashqal No Mediaplayer is not playing it..but why??

**Comment by ashqal** [comment]
Is that a flv file? Has Internet permission?

**Comment by Eldho93** [comment]
Its a m3u8 file and have internet permission

**Comment by ashqal** [comment]
This library is just a renderer, you can replace any player you want to make use the video can be decoded.

**Comment by Eldho93** [comment]
@ashqal : Please help, how do you upload video in your server and how the app streams the file ? Is it just a regular upload-download process? Is the app actually downloading the video or is it streaming ? When I tried that default video link you provided in the project in my browser it directly downloaded a 3kB file. I'm newbie to this and thats why this much questions..hope you understand..:)

**Comment by ashqal** [comment]
Cloud you give me the video url or video file?

**Comment by Eldho93** [comment]
Sure..
This is the url :
http://devotee.xyz/uploads/test/great-white-sharks-360-video-4k.m3u8
 File is attached with this mail.

On Thu, Apr 21, 2016 at 5:18 PM, Asha notifications@github.com wrote:

> Cloud you give me the video url or video file?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ashqal/MD360Player4Android/issues/11#issuecomment-212879155

## 

Yours SIncerely,
Eldhose Paul

**Comment by Eldho93** [comment]
Sorry that file type is not supported by github, so cant attach file.

**Comment by ashqal** [comment]
It seems the 4k video is not support on mobile. Please try the 1080p video.

**Comment by Eldho93** [comment]
I downloaded that video from youtube as mp4 and converted to m3u8 using
Brorsoft video converter. Could that be the reason?

On Thu, Apr 21, 2016 at 5:26 PM, Asha notifications@github.com wrote:

> It seems the 4k video is not support on mobile. Please try the 1080p video.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ashqal/MD360Player4Android/issues/11#issuecomment-212881962

## 

Yours SIncerely,
Eldhose Paul

**Comment by ashqal** [comment]
I think there is some problem with your m3u8.
