### ISSUE TITLE
如何增加录制功能呢

### ISSUE THREAD

**Issue by LaoMengFlutter** [ashqal/MD360Player4Android#111]
如何增加录制功能呢

**Comment by ashqal** [comment]
两个方面，
1.如果要原视频的录制，找一下ijk或者ffmpeg相关的资料
2.如果要渲染出来的视频的录制，GLTextureView提供了截屏的功能，实时渲染+录制性能肯定吃不消的

**Comment by LaoMengFlutter** [comment]
我们需要实时渲染+录制，https://github.com/cha007/grafika  和https://github.com/saki4510t/AudioVideoRecordingSample 是2个比较好的例子，你看能不能帮助我下，当然可以是有偿的，谢谢了。

**Comment by ashqal** [comment]
Sorry, closed. Not in plan.
