### ISSUE TITLE
小米2手机PROJECTION_MODE_SPHERE模式下会花屏

### ISSUE THREAD

**Issue by mamiaokui** [ashqal/MD360Player4Android#115]
集成进我们的app就会这样子了。
使用PROJECTION_MODE_STEREO_SPHERE不会。
是否有解决方法？
![s](https://cloud.githubusercontent.com/assets/2769377/18772536/68744784-817a-11e6-8c3b-c159de1e96c5.jpg)

**Comment by ashqal** [comment]
麻烦提供下小米2的系统版本
