### ISSUE TITLE
Black stripes from stitching on video..

### ISSUE THREAD

**Issue by timonchev** [ashqal/MD360Player4Android#117]
Hello, I'm play video from camera with 2 360 lens, but have this black stripes.. its seam that video not stiched right..

How I can resolve it? may be can some cut video-image? or change angle?
![screenshot_20160926_104202](https://cloud.githubusercontent.com/assets/2788684/18828084/ed64d826-83de-11e6-8a89-87ecfba55109.png)

**Comment by ashqal** [comment]
It seems 2 180 degree fish eye camera, and try

``` java
MDVRLibrary.PROJECTION_MODE_MULTI_FISH_EYE_HORIZONTAL
or
MDVRLibrary.PROJECTION_MODE_MULTI_FISH_EYE_VERTICAL
```

please.

**Comment by timonchev** [comment]
Not worked properly it, I think that its bad stitched mp4..
Now I use Lg 360 cam, and work good, thanks :)

**Comment by lingyun0129** [comment]
@timonchev I have the same problem,did you fixed this issue?
