### ISSUE TITLE
三星 GT-I9508 机型崩溃, log如下

### ISSUE THREAD

**Issue by hike2008** [ashqal/MD360Player4Android#119]
java.lang.IllegalArgumentException
R array length must be 3 or 4
android.hardware.SensorManager.getRotationMatrixFromVector(SensorManager.java:1336)
com.asha.vrlib.common.VRUtil.sensorRotationVector2Matrix(VRUtil.java:30)
com.asha.vrlib.strategy.interactive.MotionStrategy.onSensorChanged(MotionStrategy.java:115)
android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:467)
android.os.MessageQueue.nativePollOnce(Native Method)
android.os.MessageQueue.next(MessageQueue.java:132)
android.os.Looper.loop(Looper.java:124)
android.app.ActivityThread.main(ActivityThread.java:5419)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:525)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
dalvik.system.NativeStart.main(Native Method)

**Comment by ashqal** [comment]
看样子像必崩，是吗？

**Comment by hike2008** [comment]
是的

**Comment by ashqal** [comment]
麻烦提供下系统版本

**Comment by hike2008** [comment]
GT-I9508(samsung)
设备
Android 4.3,level 18
系统版本
NO
ROOT
9.45G( 79.04% )
磁盘可用占比
9.43G( 79.01% )
SD卡可用占比
524.77M( 29.52% )
内存可用占比

**Comment by ashqal** [comment]
#146 貌似是这个解决方案

**Comment by ashqal** [comment]
fixed.
