### ISSUE TITLE
如何取消鱼眼效果？

### ISSUE THREAD

**Issue by reaper12** [ashqal/MD360Player4Android#12]
如何取消鱼眼效果？

**Comment by ashqal** [comment]
有直接渲染原视频的需求？

**Comment by reaper12** [comment]
鱼眼效果有可能会让人出现头晕的情况

**Comment by ashqal** [comment]
我不是很明白你的意思，目前没有特意使用鱼眼，感觉你说的鱼眼可能是嫌取景范围略大，靠近边缘的部分会呈现出这种错觉。

可以调大默认的near值，去掉边缘部分，比如glass模式就没有鱼眼的感觉

**Comment by reaper12** [comment]
glass模式下 两只眼的偏差有点大 导致的头晕

**Comment by ashqal** [comment]
我没眼镜没尝试过，不过你可以调整`MD360DirectorFactory#createDirector`里的`setEyeX`和`setLookX`

**Comment by reaper12** [comment]
OK 解决了，就等着大神把底部扭曲的问题解决了，就可以上项目了

**Comment by ashqal** [comment]
我只是个平凡的码农.....

底部扭曲我尝试了增加球面面片个数，
调整到48x48，生成了240KB的.obj文件，已经基本没有扭曲，但是最底部logo中间部分还是会有扭曲
调整到128x128，生成了3M多的.obj文件，相比48x48，效果没改进多少

感觉不太合适把logo放在片源里，但是可以有一个替代方案：
生成一个平面用于渲染logo，放在底部，把logo文件提供给库，就可以实现这个效果了
