### ISSUE TITLE
It spoils the quality of video, how some unzoom it?

### ISSUE THREAD

**Issue by timonchev** [ashqal/MD360Player4Android#120]
Hello, I have a problem that library spois the quality of 360 sphere video.
Its seem  that video so much zoomed in vr mode..

How unzoom it for better quality? may be can set fov parameter? 

For example, in app SYVR360 video quality is very good..

**Comment by ashqal** [comment]
Please try this.

``` java
@Override
protected MDVRLibrary createVRLibrary() {
    return MDVRLibrary.with(this)
            ...
            .pinchConfig(new MDPinchConfig().setMin(0.7f).setMax(8.0f).setDefaultValue(0.7f))
            .pinchEnabled(true)
            ...
            .build(R.id.gl_view);
}
```

**Comment by timonchev** [comment]
Great, thanks you!!! :)
