### ISSUE TITLE
Samsung Galaxy Nexus黑屏

### ISSUE THREAD

**Issue by juechenshiai** [ashqal/MD360Player4Android#122]
Samsung Galaxy Nexus黑屏，无法加载图片或者视频
酷派大神F2在陀螺仪模式下抖动较为严重

**Comment by ashqal** [comment]
1.谷歌三儿子已经5年了，配置有点低，如果图片、视频分辨率过高，就可能导致黑屏
2.陀螺仪数据完全来自系统底层，rom如果做得不好，特别容易出现抖动
