### ISSUE TITLE
联想 K50-t5 手机出现花屏

### ISSUE THREAD

**Issue by MaffSmile** [ashqal/MD360Player4Android#123]
手机自动模式下，旋转手机偶尔会出现手机花屏 
![image](https://cloud.githubusercontent.com/assets/22759983/19257799/2a5cc226-8fa5-11e6-8e3a-ba8ca9a3332b.png)

**Comment by ashqal** [comment]
系统是4.3吗？

**Comment by ashqal** [comment]
麻烦尝试下这个版本

``` java
dependencies {
    compile 'com.github.ashqal:MD360Player4Android:64c30c70db'
}
```

**Comment by mamiaokui** [comment]
我发现了大量机器有这个Bug， 分别是oppo r9, 魅族 mx， 可能是传感器给的值是错的， 用了旧版本也会这样。 出了切换成carboard M才没问题。
