### ISSUE TITLE
Cast video : move the camera depending on the device movements

### ISSUE THREAD

**Issue by mdefrancq** [ashqal/MD360Player4Android#130]
Hi and thank you for the amazing job !

Here's my simple problem :
I'm sending a 360 video via cast mirroring using a Presentation (so what is displayed is not the actual phone screen). 
It works well, but the movements of the device are not detected and the video remains still.

I suppose it is logic, since i am initializing the MDVRLibrary inside the Presentation that will be cast.
Is there a way to update the camera position using the android motion sensors ? 
Via the DirectorFactory ?
Would you have an example ?

here is how i initialize the lib : 

`      mVRLibraryCast = MDVRLibrary.with((Activity) context)
                     .displayMode(MDVRLibrary.DISPLAY_MODE_NORMAL)
                     .interactiveMode(MDVRLibrary.INTERACTIVE_MODE_MOTION)
                     .asVideo(new MDVRLibrary.IOnSurfaceReadyCallback() {
                        @Override
                        public void onSurfaceReady(Surface surface) {
                            playerCast.setSurface(surface);
                        }
                    })
                    .build(mSurfaceViewCast);
`
Thank you very much

**Comment by ashqal** [comment]
Please try 

`
MDVRLibrary.INTERACTIVE_MODE_CARDBOARD_MOTION
`

**Comment by mdefrancq** [comment]
Thank you, i have tried but no difference.
Is there a way to programmatically change the camera ?

**Comment by apsylone** [comment]
Any news on this ?

**Comment by ashqal** [comment]
will be released in `2.4.0`
```
getVRLibrary().updateCamera().setEyeZ(18).setPitch(90)
```
