### ISSUE TITLE
更换全景图片

### ISSUE THREAD

**Issue by jksfood** [ashqal/MD360Player4Android#131]
在当前fragment中，更换全景图片，这个改怎么办？是先销毁，再创建吗？

**Comment by ashqal** [comment]
调用notifyPlayerChanged就好了

**Comment by jksfood** [comment]
thanks

**Comment by jksfood** [comment]
mVRLibrary.notifyPlayerChanged();       好像没有作用，我的图片路径设置的是全局变量
