### ISSUE TITLE
Override mediaplayer

### ISSUE THREAD

**Issue by hidabe** [ashqal/MD360Player4Android#132]
Hi, i am trying use: https://github.com/afollestad/easy-video-player for replace MediaPlayer native element. It is possible? In the sample, using ijk, it not override the view.

Any suggest?

Regards!

**Comment by ashqal** [comment]
Yes, it is possible.

> https://github.com/afollestad/easy-video-player/blob/master/library/src/main/java/com/afollestad/easyvideoplayer/EasyVideoPlayer.java

but you need to make some changes.

let the vrlib creating the surface and pass to the easy-video-player.
