### ISSUE TITLE
Always have the same orientation

### ISSUE THREAD

**Issue by apsylone** [ashqal/MD360Player4Android#135]
Hi @ashqal !

Thanks for the great work done on your lib ! This is extremely nice 👍 

I met a problem : each time I open my application, the video loaded in Glass mode is always based on the cardinal point. I would like to have the video loaded always the same orientation does not matter of the position of the phone (oriented to the north, to the south etc).

Because now depending on where you look with the phone (Gear VR) you can have a luck to have the video nice oriented. I would like to define always the same the "zero point" when the application is launched.

Could you help me ? I think it is something easy to do, but I've not found how...

Thanks for your help !

**Comment by ashqal** [comment]
please use `Cardboard M` mode instead of `Motion` mode.
