### ISSUE TITLE
漂移的问题有人解决了么? 

### ISSUE THREAD

**Issue by liupeng110** [ashqal/MD360Player4Android#138]
rt

**Comment by liupeng110** [comment]
我用的 cardboard M&T 模式 ,测试了小米,oppo r9,魅蓝3  utovr和vr世界是正常的,vrlib会漂移      
谷歌应该已经修正过陀螺仪 偏移问题了   这个问题要怎么修复呀  有遇到同样问题的么

**Comment by liupeng110** [comment]
楼主的m&t初始角度的问题有人搞定了么 ?  谁搞定了 说一下 多谢呀

**Comment by liupeng110** [comment]
已经搞定.

**Comment by lgh3013** [comment]
请问怎么解决的

**Comment by lgh3013** [comment]
请问的是漂移的问题，漂移的问题不是always的，是sometimes的，而已只是水平方向的漂移，上下不会，我用的是nexus的手机

**Comment by liupeng110** [comment]
用群里  忍者的vrlib ，他移植了谷歌的修复漂移算法     群主没有移植修复漂移的算法

**Comment by liupeng110** [comment]
有些机型  比如三星某些机型用群主的库是正常的，有些会漂移

**Comment by liupeng110** [comment]
群主没有移植漂移修复算法，群里有人移植了

**Comment by lgh3013** [comment]
已合，暂时没有出现问题了，多谢多谢

**Comment by fengqingyundan** [comment]
上面两位，麻烦提供一下修复算法的移植方法，非常感谢

@liupeng110 @lgh3013

**Comment by reaper12** [comment]
用群主的cardboard M&T 模式也会出现漂移吗？

**Comment by liupeng110** [comment]
@fengqingyundan 群里的一个人(qq747651446)移植的，不是我

**Comment by liupeng110** [comment]
@reaper12  有些机型比如三星的note xx不漂移,我测试的大部分手机会漂移的

**Comment by reaper12** [comment]
用忍者的库貌似不能设置touch模式，你遇到这个问题了吗？

**Comment by liupeng110** [comment]
@reaper12   群里有个可以touch的库

**Comment by reaper12** [comment]
@liupeng110 那个就是我写的。。。

**Comment by liupeng110** [comment]
vrlib170101.zip

**Comment by liupeng110** [comment]
后续的版本我没测了

**Comment by liupeng110** [comment]
@reaper12

**Comment by reaper12** [comment]
喔  我自己封装了个库，上传到群里
