### ISSUE TITLE
陀螺仪（Callback if the TYPE_ROTATION_VECTOR is NOT supported）

### ISSUE THREAD

**Issue by jksfood** [ashqal/MD360Player4Android#14]
大侠，我在oppo和华为的手机上运行时，视频无法播放，console提示两个相关的错误：MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present、MotionStrategy: TYPE_ROTATION_VECTOR sensor not support!。这该怎么办？

**Comment by ashqal** [comment]
如果机器不支持TYPE_ROTATION_VECTOR，就不支持motion模式了，
机器是否支持，可以在安兔兔上查看到
![image](https://cloud.githubusercontent.com/assets/5126517/14735107/98a34060-08a1-11e6-915f-ae3dfab636cc.png)

**Comment by jksfood** [comment]
我的意思是在代码中是不是可以判断出来？然后我好给个弹出框提示下

**Comment by ashqal** [comment]
好的 没问题

**Comment by jksfood** [comment]
thank you!

**Comment by ashqal** [comment]
add `ifNotSupport` to builder, e.g. [VideoPlayerActivity#createVRLibrary](https://github.com/ashqal/MD360Player4Android/blob/master/app/src/main/java/com/asha/md360player4android/VideoPlayerActivity.java)

``` java
.ifNotSupport(new MDVRLibrary.INotSupportCallback() {
    @Override
    public void onNotSupport(int mode) {
        String tip = mode == MDVRLibrary.INTERACTIVE_MODE_MOTION
                ? "onNotSupport:MOTION" : "onNotSupport:" + String.valueOf(mode);
        Toast.makeText(VideoPlayerActivity.this, tip, Toast.LENGTH_SHORT).show();
    }
})
```
