### ISSUE TITLE
锤子一代产品上陀螺仪无法直接使用问题

### ISSUE THREAD

**Issue by hanbim520** [ashqal/MD360Player4Android#143]
使用您的插件在锤子1带产品上运行，发现陀螺仪无法正常使用，
private void initVRLibrary(){
        // new instance
        mVRLibrary = MDVRLibrary.with(this)
                .displayMode(MDVRLibrary.DISPLAY_MODE_NORMAL)
                .interactiveMode(MDVRLibrary.INTERACTIVE_MODE_MOTION_WITH_TOUCH)
                .asVideo(new MDVRLibrary.IOnSurfaceReadyCallback() {
                    @Override
                    public void onSurfaceReady(Surface surface) {
                        // IjkMediaPlayer or MediaPlayer
                        mMediaPlayerWrapper.getPlayer().setSurface(surface);
                    }
                })
                .build(R.id.gl_view);
    }

锤子的系统是Android 4.4.2，基带是2.0.1-00154，内核3.4.0，处理器Qualcomm MSM 8974，陀螺仪权限已经通过menifest文件强行加权限。

希望您能测试下，或者需要我提供什么数据给您分析，也希望是我自己有代码上的错误，希望您能指正。

**Comment by hanbim520** [comment]
下午的时候 我已经解决，好似某些参数不设定的话，无法使用陀螺仪，虽然使用了MDVRLibrary.INTERACTIVE_MODE_MOTION_WITH_TOUCH 等motion参数，感觉应该设置默认值比较好。

**Comment by Alen-Liu** [comment]
哪些参数不设定会导致无法使用陀螺仪
