### ISSUE TITLE
Unclear about installation instructions

### ISSUE THREAD

**Issue by yussidivnall** [ashqal/MD360Player4Android#147]
Where does MediaPlayerActivity come from? couldn't find it in source tree.

**Comment by jplgarcia** [comment]
Me neither, have anyone found the answer yet?

**Comment by yussidivnall** [comment]
I ended up using Google VR.
https://developers.google.com/vr/android/samples/vrview

**Comment by jplgarcia** [comment]
But does it work with video or only still images?

**Comment by yussidivnall** [comment]
Both, for video you use this https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/video/VrVideoView

**Comment by ashqal** [comment]
`MediaPlayerActivity ` is just a simple activity.
