### ISSUE TITLE
图片有时候加载的较慢并且是又是还加载不上

### ISSUE THREAD

**Issue by zzggxx** [ashqal/MD360Player4Android#148]
图片有时候加载的较慢并且是又是还加载不上,摩托罗拉手机上表现的很明显也是很容易复现的.求解答

**Comment by liupeng110** [comment]
换个加载图片的框架试试

**Comment by ashqal** [comment]
显示不出来可能是分辨率太高，机型低端，贴图不支持这么大比例的，然后表现是黑屏，你可能就认为是加载慢了...
