### ISSUE TITLE
About Image player part

### ISSUE THREAD

**Issue by ZhengzhongSun** [ashqal/MD360Player4Android#15]
想问下博主，在处理全景图片播放时，为什么要采取代码中的那么复杂的方式？
private ThreadLocal<Integer> mLocalGLTexture = new ThreadLocal<>();
而不是直接把图片load进来作为texture就好了？谢谢！

**Comment by ashqal** [comment]
两个glThread共用了一个MDRenderer，从不同线程进来，不同的glContext，需要获取对应的textureId，刚好TheadLocal可以解决这个问题

**Comment by ZhengzhongSun** [comment]
同一张图片不可以只给一个textureID吗？

**Comment by ashqal** [comment]
我感觉是不行的 textureId是对应glContext下创建的texture

**Comment by ZhengzhongSun** [comment]
这里为什么要用多个thread呢？都是同一个texture为什么要在不同的contex下创建呢？

**Comment by ashqal** [comment]
glass模式下就得有2个glSurfaceView，对应2个glContext、GLThread

**Comment by ZhengzhongSun** [comment]
我现在先定义了一个glviewport（左半屏幕），运行您的全景图片，然后再定义了glviewport（右半屏幕）重新定义各种矩阵和shader。单独运行的话都是好的，同时运行的话，glviewport（左半部分）就没有东西了，只有右半部分有东西。可以这么使用吗？您感觉可能的原因是什么？

**Comment by ashqal** [comment]
没看懂，2个GLSurfaceView吗

**Comment by ZhengzhongSun** [comment]
1个GLSurfaceView里

**Comment by ashqal** [comment]
感谢，现在已经改为1个glSurfaceView，当时太无知，再次感谢
