### ISSUE TITLE
播放视频时添加一个MDWidgetPlugin，第一次能在屏幕中看见，旋转一定角度后再次添加就看不见了

### ISSUE THREAD

**Issue by xmzd** [ashqal/MD360Player4Android#157]
播放视频时添加一个MDWidgetPlugin，第一次能在屏幕中看见，旋转一定角度后，再次添加，就看不见了，也就是说，不管在什么角度下添加，只有旋转到第一次的角度才能看见

**Comment by liupeng110** [comment]
同求,热点跟随 问题有没有好的办法解决

**Comment by ashqal** [comment]
尝试了下这种方式，发现使用热点跟随这种方式就无法使用头控了，请问你们是什么场景下需要这个功能？是直接屏幕上点击的操作方式吗？

**Comment by liupeng110** [comment]
vr的模式啊左右眼那种，不屏幕点击啊
场景：左右眼模式播放vr视频,加个进度条（热点）
转个方向，低头让进度条（热点）显示   抬头进度条消失  
关键 进度条（热点）也要支持碰撞检测  就是说能不能动态的获取到当前焦点的坐标 （不考虑z轴或者z轴固定的情况）,添加热点                         

 百度vr那个好像是可以的

**Comment by liupeng110** [comment]
我感觉是找到当前 射线   跟z轴的焦点坐标 就能基本解决这个问题

**Comment by ashqal** [comment]
@liupeng110 你这样考虑一下，当进度条跟随当前视角一起动后，视角中心点永远就选不中进度条了

**Comment by liupeng110** [comment]
@ashqal 你说的这个情况就相当于直接把进度条写在 最顶层布局。
如果可以找到射线跟z轴的交点，就能根据交点坐标  动态设置热点的位置
热点是固定不变的,我们只是动态添加删除

**Comment by ashqal** [comment]
@liupeng110 我明白你的意思了，我开放出修改热点Position的方法，和获取当前视角中心position的方法，就可以实现这个需求了， @xmzd 符合你的预期吗？

**Comment by liupeng110** [comment]
@ashqal  多谢大佬

**Comment by xmzd** [comment]
@ashqal 我的需求是这样的，在左右眼模式下播放VR视频时，低头显示播放、暂停、上一个以及下一个这种功能热点，通过头控，可以执行暂停等操作，再抬头隐藏热点，旋转一定角度，再次低头，显示热点，通过头控，可以继续播放

**Comment by ashqal** [comment]
@xmzd 恩 了解了 和 @liupeng110 一个意思

**Comment by xmzd** [comment]
@ashqal 多谢大佬！！！

**Comment by ashqal** [comment]
add a hotpost with tag.
```
findViewById(R.id.button_add_hotspot_front).setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        MDHotspotBuilder builder = MDHotspotBuilder.create(mAndroidProvider)
                .size(4f,4f)
                .provider(MDUtil.getDrawableUri(activity, R.drawable.moredoo_logo))
                .title("front logo")
                .tag("tag-front")
                .position(MDPosition.newInstance().setZ(-12.0f).setY(-1.0f));
        MDHotspotPlugin hotspot = new MDHotspotPlugin(builder);
        hotspot.rotateToCamera();
        plugins.add(hotspot);
        getVRLibrary().addPlugin(hotspot);
    }
});
```

find the hotpost and rotate to camera.
```
findViewById(R.id.button_rotate_to_camera_plugin).setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        IMDHotspot hotspot = getVRLibrary().findHotspotByTag("tag-front");
        if (hotspot != null){
            hotspot.rotateToCamera();
        }
    }
});
```
