### ISSUE TITLE
Reset "center" in video.

### ISSUE THREAD

**Issue by Bododev** [ashqal/MD360Player4Android#159]
I don't know if i should identify this as a bug or a feature request because it's both of them. As many should realized when you start a video, it's position is influenced by phone's position. It would be good a command to reset the video in center no matter of your current position. I have tried to do something like that, but without success. Thanks for your time and for you beautiful player.

**Comment by ashqal** [comment]
please use `Cardboard M` mode instead of `Motion` mode.
