### ISSUE TITLE
oppo手机无法播放

### ISSUE THREAD

**Issue by jksfood** [ashqal/MD360Player4Android#16]
我用的oppo手机，没有陀螺仪，然后就无法播放。黑屏。带陀螺仪的nexus可以正常播放，请问是为什么？Could not find class 'android.view.WindowInsets', referenced from method com.flyco.banner.widget.LoopViewPager.LoopViewPager.access$super

**Comment by jksfood** [comment]
04-24 02:40:50.529 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.529 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.529 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.media.session.MediaController', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.539 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.widget.Toolbar', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.539 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.539 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.539 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.549 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.559 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.app.assist.AssistContent', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.559 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.view.SearchEvent', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.559 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.asha.md360player4android.MD360PlayerActivity.access$super
04-24 02:40:50.619 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.619 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.619 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.media.session.MediaController', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.619 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.widget.Toolbar', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.619 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.619 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.619 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.619 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.629 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.app.assist.AssistContent', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.629 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.view.SearchEvent', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.629 26791-26791/com.asha.md360player4android E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.asha.md360player4android.VideoPlayerActivity.access$super
04-24 02:40:50.689 26791-26791/com.asha.md360player4android E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present

**Comment by jksfood** [comment]
是不是手机支持陀螺仪的才能播放？不支持的就播放不起来？

**Comment by ashqal** [comment]
不是这个库的问题，建议clean下试试？

**Comment by jksfood** [comment]
好的，我马上回去试试

**Comment by jksfood** [comment]
确实  不是您的库的问题。但是我很奇怪，你的程序里的网址http://vod.moredoo.com/u/7575/m3u8/854x480/25883d97c738b1be48d1e106ede2789c/25883d97c738b1be48d1e106ede2789c.m3u8可以正常的播放，但为什么我给的http://doubo.ufile.ucloud.com.cn/qihuansenlin.mp4就不能播放？但是我在nexus手机上，这个网址就能播放，究竟哪里出了问题？望解答指点下

**Comment by jksfood** [comment]
出现问题的是在oppo手机上

**Comment by ashqal** [comment]
http://doubo.ufile.ucloud.com.cn/qihuansenlin.mp4
我这里也放不出来，感觉是MediaPlayer的关系，视频分辨率略高，解码不了了

```
04-24 18:19:16.370 416-25911/? E/NuPlayerDecoder: Failed to configure OMX.qcom.video.decoder.avc decoder (err=-1010)
04-24 18:19:16.390 416-25862/? E/NuPlayer: received error(0xfffffc0e) from video decoder, flushing(0), now shutting down
04-24 18:19:16.391 22290-22307/com.asha.md360player4android E/MediaPlayer: error (1, -1010)
04-24 18:19:16.392 22290-22290/com.asha.md360player4android E/MediaPlayer: Error (1,-1010)

```

**Comment by jksfood** [comment]
那该怎么办？不用mediaPlayer吗？用IjkVRPlayer吗？是不是跟手机硬件相关？我项目中大部分的视频资源应该都是这种的

**Comment by ashqal** [comment]
把MediaPlayer替换成IjkMediaPlayer即可

**Comment by jksfood** [comment]
好的  我试试

**Comment by ashqal** [comment]
我换好了，效果非常棒，感谢开源

**Comment by ashqal** [comment]
目前有很大几率crash 可能是调用方式不对 reopen

**Comment by jksfood** [comment]
http://doubo.ufile.ucloud.com.cn/qihuansenlin.mp4    这个视频你那儿能播放了？为什么我在oppo手机上还是不行？      04-24 20:37:57.693 24477-25483/com.asha.md360player4android:vrPlayer E/MediaPlayer: error (1, -2147483648)

**Comment by ashqal** [comment]
是这次提交报的？
b20db00240c55a8ee516f51c0ae4f779dbbfab07 ？

**Comment by jksfood** [comment]
是的  我看到你用的IjkMediaPlayer了

**Comment by jksfood** [comment]
会不会有什么参数可以设置的？

**Comment by ashqal** [comment]
`MediaPlayerWrapper`

``` java
public void init(){
    mPlayer = new AndroidMediaPlayer();
    mPlayer.setOnPreparedListener(this);
}
```

改为

``` java
public void init(){
    mPlayer = new IjkMediaPlayer();
    mPlayer.setOnPreparedListener(this);
}
```

**Comment by ashqal** [comment]
ijk换成0.4.5不会崩溃了，已提交，你试一下

**Comment by jksfood** [comment]
嗯嗯  可以了   感谢！
