### ISSUE TITLE
关于eyePick问题

### ISSUE THREAD

**Issue by AppUU** [ashqal/MD360Player4Android#161]
if (System.currentTimeMillis() - hitTimestamp > 5000) { 
     getVRLibrary().setEyePickEnable(false);
     getVRLibrary().resetEyePick();
  }
这样触发一个热点5s后不可触发，如何再次触发（我想只要eye没在热点上移走，无论多久就执行一次，eye移至其他热点仍可触发）

**Comment by ashqal** [comment]
这个...你存个变量 标记为已触发，一移走就把变量恢复就可以了
