### ISSUE TITLE
请问作者有没有获取手机左右翻转角度的方法？

### ISSUE THREAD

**Issue by geeeeeeeek** [ashqal/MD360Player4Android#163]
请问作者有没有获取手机左右翻转角度的方法？ 我看网上很多使用SensorManager.getRotationMatrix() 方法的。但是数学太差。请问您有什么办法获取左右翻转角度？例如这个例子的，https://play.google.com/store/apps/details?id=com.fyusion.fyuse
或者这个的：https://play.google.com/store/apps/details?id=com.vivoti.phogy

**Comment by ashqal** [comment]
最近也在看这方面的资料，学习了`Quaternion`的表示方法，您可以把rotationMatrix转为`MDQuaternion`，然后通过`MDQuaternion`可以获得欧拉角`yaw`,`pitch`,`roll`；

当然你也可以直接把rotationMatrix转为欧拉角，可以使用`VRUtil#getEulerAngles`;

上述提到的代码都在dev-m240的这个https://github.com/ashqal/MD360Player4Android/commit/3eebcd369031c713c798f89d0a03df18a038502b commit上，可以参考下

**Comment by ashqal** [comment]
will be released in `2.4.0`.

```
getVRLibrary().getDirectorBrief()
```

```
public class MDDirectorBrief {
    private float pitch;
    private float yaw;
    private float roll;
}
```
