### ISSUE TITLE
关于偏移角的问题

### ISSUE THREAD

**Issue by lgh3013** [ashqal/MD360Player4Android#165]
旧的代码可以通过MDPosition.sOriginalPosition.setPitch(90)；来设置转变的角度，但最近的改动去掉了这个接口，另外MD360Director.builder().setRoll(180).build();这个只在create的时候被设
现在问题是，现在如何在create后，如果想改变角度，如何调用。谢谢

**Comment by ashqal** [comment]
1.MDPosition.sOriginalPosition是全局共享的原点，为了节约内存用的，直接修改会导致所有引用sOriginalPosition的都放生变化，所以我限制了对它的修改；

2.你说的问题确实存在，M2-4版本我开放修改director的接口吧...

**Comment by ashqal** [comment]
will be released in `2.4.0`
```
getVRLibrary().updateCamera().setEyeZ(18).setPitch(90)
```
