### ISSUE TITLE
360 effect and navigation isn't working in my integrated project

### ISSUE THREAD

**Issue by lazarusvc** [ashqal/MD360Player4Android#166]
Hi,

I am trying to integrate this into my app, but I am not getting anywhere. The 360 video is being played (Viewed), but can't navigate.

Also is this how I should implement MediaPlayer?
`
    private void initVRLibrary(){
        // new instance
        mVRLibrary = MDVRLibrary.with(this)
                .displayMode(MDVRLibrary.DISPLAY_MODE_NORMAL)
                .interactiveMode(MDVRLibrary.INTERACTIVE_MODE_MOTION)
                .asVideo(new MDVRLibrary.IOnSurfaceReadyCallback() {
                    @Override
                    public void onSurfaceReady(Surface surface) {
                        // IjkMediaPlayer or MediaPlayer
                        media_player.setSurface(surface);
                    }
                })
                .build(R.id.surface_view);
`

**Comment by ashqal** [comment]
Sorry, the vrlib is only focus on renderer.
You should impl the seek/play/pause/stop by yourself.

The MediaPlayer is a class in Android Framework.
