### ISSUE TITLE
Sphere Projection upside down when in glass mode

### ISSUE THREAD

**Issue by gbrlsnts** [ashqal/MD360Player4Android#167]
Hello, I was trying out your great library and found out that when using sphere projection mode and glass mode, the image is upside down. You can look at the screenshots I provided below, at the bottom.

I am using version 2.3.0.

![2017-05-07 19 02 14](https://cloud.githubusercontent.com/assets/3952623/25784141/630f2f64-3360-11e7-8056-636da1714a6a.png)
![2017-05-07 18 59 14](https://cloud.githubusercontent.com/assets/3952623/25784143/65be143c-3360-11e7-956f-68fa862d2ab5.png)

And here is the test image:
![vr](https://cloud.githubusercontent.com/assets/3952623/25784178/52d82eec-3361-11e7-9858-79bec5986dc2.jpg)

**Comment by gbrlsnts** [comment]
Update: Apparently it only happens when anti distortion is enabled. If I disable it, the image is shown correctly.

For video, when barrel distortion is enable it shows fine and disabled it is upside down. I use multi fish eye for video.

**Comment by ashqal** [comment]
Thanks!

fixed on `dev-m240`
```
dependencies {
	compile 'com.github.ashqal:MD360Player4Android:dev-m240-SNAPSHOT'
}
```
