### ISSUE TITLE
视频能播放本地文件嘛？(Play Local File)

### ISSUE THREAD

**Issue by 3660628** [ashqal/MD360Player4Android#17]
我看了代码里面有一段是openLocalFile在MediaPlayerWrapper.java

**Comment by ashqal** [comment]
当然可以了，具体麻烦搜索一下MediaPlayer相关的api

**Comment by 3660628** [comment]
我试了试。。。MediaPlayer只能播放绝对路径的那种“file:///”，不是能setdatasource给res，IMediaPlayer好像不能传递FileDescriptor。下面这种就会出错。。。说传入参数不匹配
AssetFileDescriptor fileDescriptor = getAssets().openFd("1.mp4");
m_mediaPlayer.setDataSource(fileDescriptor.getFileDescriptor(),fileDescriptor.getStartOffset(), fileDescriptor.getLength()); //就是这里不对
设置datasource

**Comment by ashqal** [comment]
我试了下AndroidMediaPlayer的实现可以放，IjkMediaPlayer的放不了，应该是IjkMediaPlayer的问题

**Comment by yangkai3** [comment]
我解决了这个问题，在androidManifest中加上读取sd卡权限就可以了，不是 ijk 的问题

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

**Comment by ashqal** [comment]
@yangkai3 他说的是播放assets里的或者播放res/raw里的视频

**Comment by yangkai3** [comment]
这样是可以使用 asset 文件夹下 视频的：

``` java
AssetManager am = context.getResources().getAssets();
      final InputStream is = am.open("2.mp4");
      mPlayer.setDataSource(new IMediaDataSource() {
        @Override
        public int readAt(long position, byte[] buffer, int offset, int size) throws IOException {
          return is.read(buffer, offset, size);
        }

        @Override
        public long getSize() throws IOException {
          return is.available();
        }

        @Override
        public void close() throws IOException {
          is.close();
        }
      });
    } catch (IOException e) {
      e.printStackTrace();
    }
```
