### ISSUE TITLE
Image is Flipped!

### ISSUE THREAD

**Issue by sinaone1** [ashqal/MD360Player4Android#173]
Dear Ashqal.
First thank you about MD360Player4Android.
I don't have any problem with old version of MD360Player4Android.
But i update its in my application and now my images show flipped.
For example if we have this original image:

![1](https://user-images.githubusercontent.com/11288019/28108748-d4ebecba-6701-11e7-938e-c704f1433ad2.jpg)

when i show its with BitmapPlayerActivity , it shows flipped like this 

![2](https://user-images.githubusercontent.com/11288019/28108791-fad7b6b6-6701-11e7-8b18-f1b29566aa29.jpg)

How could i fix it?
thank you.

**Comment by daljeet33** [comment]
How did you manage to make it work?
