### ISSUE TITLE
Stereo 360 video

### ISSUE THREAD

**Issue by SaniokUA** [ashqal/MD360Player4Android#175]
Can this player play a 360 stereo video?

**Comment by SaniokUA** [comment]
PROJECTION_MODE_STEREO_SPHERE only with this dep. parameter works...
How i can know what the type of video (Stereo or not)

**Comment by ashqal** [comment]
The Stereo Video File is a standard video file, there is no way to known the type of the video. 
Or maybe you can define the type of the video in json from server side.
