### ISSUE TITLE
PROJECTION_MODE_PLANE_FULL 模式下不能缩放

### ISSUE THREAD

**Issue by xiekelin** [ashqal/MD360Player4Android#178]
MDVRLibrary mVRLibrary =  MDVRLibrary.with(mActivity)
                .displayMode(MDVRLibrary.DISPLAY_MODE_NORMAL)
                .interactiveMode(MDVRLibrary.INTERACTIVE_MODE_TOUCH)
                .projectionMode(MDVRLibrary.PROJECTION_MODE_PLANE_FULL)
                .asVideoWithYUV420PProvider(new MDVRLibrary.IYuvImageProvider() {
                    @Override
                    public void onProvideYuvImage(final MD360YUV420VideoTexture.Callback callback) {
                        if(yuvFrame != null) {
                            callback.texture(yuvFrame);
                        }
                    }
                })
                .pinchEnabled(true)
//                .listenGesture(new MDVRLibrary.IGestureListener(){
//
//                    @Override
//                    public void onClick(MotionEvent e) {
//                        LayoutInflater.from(mActivity).inflate(android.R.layout.);
//                    }
//                })
                .takePicHandler(new MDVRLibrary.TakePicHandler() {
                    @Override
                    public void onTakePic(int width, int height, Bitmap inBitmap) {
                        callbackHandler.ontakePic(inBitmap);
                    }
                })
                .build(glViewId);
不能缩放GLSurfaceView界面。是要自己去实现吗？

**Comment by ashqal** [comment]
这个模式没必要伸缩吧..

**Comment by xiekelin** [comment]
额，需求是要可以伸缩。运行demo在PROJECTION_MODE_PLANE_FULL模式时，放大手势时，图像直接变黑了。

**Comment by lookfuyao** [comment]
自己控制下，plane模式禁止掉pinch（setPinchEnabled）

**Comment by ashqal** [comment]
@xiekelin 放大后，摄像头near可能已经超过平面所在的坐标，所以全黑了

**Comment by xiekelin** [comment]
好难改，这个功能，搞了一个星期都没搞定，大神这个缩放可不可以加上去啊？

**Comment by ashqal** [comment]
```java
private class OrthogonalDirector extends MD360Director{

    private final float sNearBase;

    private OrthogonalDirector(Builder builder) {
        super(builder);
        sNearBase = getNear();
    }

    @Override
    public void setDeltaX(float mDeltaX) {
        // nop
    }

    @Override
    public void setDeltaY(float mDeltaY) {
        // nop
    }

    @Override
    public void updateSensorMatrix(float[] sensorMatrix) {
        // nop
    }

    @Override
    protected void updateProjection(){
        planeScaleCalculator.setViewportRatio(getRatio());
        planeScaleCalculator.calculate();
        float scale = sNearBase / getNear();
        final float left = - planeScaleCalculator.getViewportWidth() / 2 * scale;
        final float right = planeScaleCalculator.getViewportWidth() / 2 * scale;
        final float bottom = - planeScaleCalculator.getViewportHeight() / 2 * scale;
        final float top = planeScaleCalculator.getViewportHeight() / 2 * scale;
        final float far = 500;
        Matrix.orthoM(getProjectionMatrix(), 0, left, right, bottom, top, 1, far);
    }
}
```
修改下`PlaneProjection.java`里的内部类`OrthogonalDirector`

**Comment by xiekelin** [comment]
恩恩，后面看源码知道了怎么改，谢谢！
