### ISSUE TITLE
画面卡顿 

### ISSUE THREAD

**Issue by jksfood** [ashqal/MD360Player4Android#18]
http://recorded.live.doubo.tv/realrealcomp.mp4
这类地址的视频播放起来画面卡顿，像是慢动作，而且声音跟画面不同步，声音应该是正常速率播放的，但是画面没跟上。会不会跟帧率有关？在哪里可以设置帧率吗？

**Comment by ashqal** [comment]
这视频第一帧好眼熟...

**Comment by jksfood** [comment]
我也是从网上抓的视频，大侠

**Comment by jksfood** [comment]
可不可以指点一下？

**Comment by ashqal** [comment]
最近在准备组内的一个分享，比较忙，不好意思

**Comment by jksfood** [comment]
哪里哪里  没事  我自己研究下先  谢谢

**Comment by jksfood** [comment]
可以给个大致的思路吗？一下子看不太懂，是不是有什么参数设置下就可以了的？

**Comment by jksfood** [comment]
不好意思啊

**Comment by jksfood** [comment]
https://github.com/fbsamples/360-video-player-for-android这个人的项目   画面不卡，但是不带重力感应和双屏，我看了你们都用的opengl   但是用法不一样

**Comment by jksfood** [comment]
初步发现是IjkMediaPlayer的原因

**Comment by kissazi2** [comment]
@jksfood 能说明下具体是什么原因吗？

**Comment by jksfood** [comment]
我在nexus上试的，用你之前那个没有替换为IjkMediaPlayer的版本播放视频不卡，但是，最新版本，也就是IjkMediaPlayer版的播放就很卡，我在怀疑是不是IjkMediaPlayer使用方法的问题，是不是可以开启硬解码之类的

**Comment by jksfood** [comment]
我用了gtihub其他几个IjkMediaPlayer  demo，都出现这种现象

**Comment by ashqal** [comment]
应该是视频太大了，ffmpeg软解解不过来

**Comment by jksfood** [comment]
130M多的视频，如果是软解不行，那请问需要怎么设置呢？

**Comment by jksfood** [comment]
时长3分多钟

**Comment by ashqal** [comment]
我是指分辨率，3840x1920了，现在主流超清是1920x1080

**Comment by jksfood** [comment]
嗯 确实 这个视频时3840*1920的

**Comment by jksfood** [comment]
那。。。无解了？！

**Comment by jksfood** [comment]
help!......大侠

**Comment by ashqal** [comment]
Android设备本身就配置普遍偏低，不像iPhone，所以好像没办法

**Comment by jksfood** [comment]
****谢谢大侠

**Comment by jksfood** [comment]
开启了ijkplayer的硬解码，好多了

**Comment by jksfood** [comment]
硬解码后，4K分辨率的视频，在稍微好点的手机上还行，低端手机卡的没话说

**Comment by jksfood** [comment]
mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
        mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
//        mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "overlay-format", IjkMediaPlayer.SDL_FCC_YV12);
        mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "overlay-format", IjkMediaPlayer.SDL_FCC_RV32);
        mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 60);
        mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max-fps", 0);
//        mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "fps", 60);

```
    mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);
```

**Comment by ashqal** [comment]
提交个PR吧

**Comment by jksfood** [comment]
嗯  好的  稍等
