### ISSUE TITLE
最新版本画面全是反着的

### ISSUE THREAD

**Issue by zhuyifan2013** [ashqal/MD360Player4Android#181]

**Comment by ashqal** [comment]
```java
dependencies {
    compile 'com.github.ashqal:MD360Player4Android:2.4.1'
}
```
是这个版本吗？

**Comment by zhuyifan2013** [comment]
是的 `    compile 'com.github.ashqal:MD360Player4Android:2.4.1' `

用的是 GLSurfaceView ，反着具体表现在 镜面反转+ 上下颠倒

**Comment by ashqal** [comment]
我刚试了下都是好的，这个问题在之前合并PR后产生，麻烦再检查下代码版本..

**Comment by zhuyifan2013** [comment]
代码版本没有错，我下载下来 build 还是一样的问题，不过可能是哪里的问题？ 我 Debug 一下看看？

**Comment by ashqal** [comment]
1.是图片还是视频还是？
2.是否开启反畸变？

**Comment by zhuyifan2013** [comment]
是视频；
这是配置参数，没有开启反畸变：
` return MDVRLibrary.with(getContext())
                .displayMode(MDVRLibrary.DISPLAY_MODE_NORMAL)
                .interactiveMode(MDVRLibrary.INTERACTIVE_MODE_MOTION_WITH_TOUCH)
                .projectionMode(MDVRLibrary.PROJECTION_MODE_PLANE_FULL)
                .asVideo(new MDVRLibrary.IOnSurfaceReadyCallback() {
                    @Override
                    public void onSurfaceReady(Surface surface) {
                        mSurface = surface;
                        if (mMediaPlayer != null) {
                            mMediaPlayer.setSurface(surface);
                        }
                    }

                })
                .ifNotSupport(new MDVRLibrary.INotSupportCallback() {
                    @Override
                    public void onNotSupport(int mode) {
                        String tip = mode == MDVRLibrary.INTERACTIVE_MODE_MOTION ? "onNotSupport:MOTION" :
                                "onNotSupport:" + String.valueOf(mode);
                    }
                })
                .build(mSurfaceRenderView);
`

**Comment by ashqal** [comment]
mMediaPlayer是使用ijk的实现吗？

**Comment by zhuyifan2013** [comment]
是的

**Comment by ashqal** [comment]
你发我demo工程 我跑一下看看吧

**Comment by zhuyifan2013** [comment]
我的是 React Native 的项目，您跑起来可能很麻烦  🤣  或者我把相关部分的代码发给你？

**Comment by ashqal** [comment]
[app-debug.apk.zip](https://github.com/ashqal/MD360Player4Android/files/1221887/app-debug.apk.zip)

跑一下这个apk试试 看看是否正常

**Comment by zhuyifan2013** [comment]
嗯  正常的

**Comment by ashqal** [comment]
项目中是否放了res/per_pixel_vertex_shader.glsl文件？
最新的作为lib引入，在资源合并的时候被丢弃

**Comment by zhuyifan2013** [comment]
嗯，我的 res 里有 🤣  所以我应该去掉是吧

**Comment by zhuyifan2013** [comment]
我有三个 per_pixel_fragment_shader per_pixel_fragment_shader_bitmap per_pixel_vertex_shader

**Comment by ashqal** [comment]
都删了吧 通过gradle方式引用
