### ISSUE TITLE
如果让vr眼镜模式  左眼和有眼的画面x显示画面的不一样

### ISSUE THREAD

**Issue by li504799868** [ashqal/MD360Player4Android#182]
我们想让左眼显示左边画面  右眼显示右边的画面，请问这个有什么办法吗

**Comment by li504799868** [comment]
我仔细的看了一下 大概是让右眼显示的画面旋转了 -180度  ，咱们有直接设置的方法吗

**Comment by JM-TD** [comment]
这个需要自己修改吧，加个插件，先弄两个framebuffer，分别保存左半部分和右半部分，render里面再把两个部分画出来。

**Comment by ashqal** [comment]
https://github.com/ashqal/MD360Player4Android/wiki/Advanced-Usage#md360director-customize-since-120

左右眼不一样

**Comment by li504799868** [comment]
我看了这个wiki，但是找不到setAngle这个方法，是这个方法已经废弃替换成其他的方法了吗？

private static class DirectorFactory extends MD360DirectorFactory{
    @Override
    public MD360Director createDirector(int index) {
        switch (index){
            // setAngle: angle to rotate in degrees
            case 1:   return MD360Director.builder().setAngle(20).setEyeX(-2.0f).setLookX(-2.0f).build();
            default:  return MD360Director.builder().setAngle(20).build();
        }
    }
}

**Comment by ashqal** [comment]
试试setRoll setYaw setPatch

**Comment by li504799868** [comment]
非常感谢您耐心的回答我的这些逗比问题  刚刚我又仔细研究了一下 发现有一个模式PROJECTION_MODE_STEREO_SPHERE_HORIZONTAL可以满足我的需求 只是我之前没发现 测试过程没准备好 虽然整个过程走了个大弯路  但是对这个框架的理解和使用也提高了很多

**Comment by li504799868** [comment]
再次感谢

**Comment by li504799868** [comment]
顺便问另一个问题  我看了https://github.com/ashqal/MD360Player4Android/issues/32 这个问题  怎么设置能让vr显示的尺寸大一点呢

**Comment by ashqal** [comment]
```java
MDVRLibrary.Builder#pinchConfig
MDVRLibrary#setPinchConfig
```
`MDPinchConfig#setMin(0.7)`
