### ISSUE TITLE
请教一下原理问题

### ISSUE THREAD

**Issue by Millertoken** [ashqal/MD360Player4Android#19]
你好，我在自己的工程里面使用您的DEMO。我想请教一下你实现360全景视频和双屏幕的原理是什么呢？我对Opengl不太熟悉，如果可以的话，最好能大概描述一下关键性代码和类，这应该是很多同学也很关心的。非常感谢，不胜感激。

**Comment by ashqal** [comment]
双屏我是看了这篇文章实现的，你可以参考下
[ANDROID高性能图形处理之二.OPENGL ES](http://tangzm.com/blog/?p=20)

另外原理就是用opengles，把视频帧贴图到一个球面上，从球心往外看就可以了

**Comment by Millertoken** [comment]
@ashqal 好的，我学习一下。感谢。

**Comment by Millertoken** [comment]
@ashqal 还想请教一个问题。有些应用实现影院模式（如暴风魔镜，视频view只占屏幕的一小部分，其余界面实现了一个电影院的感觉），然后还画了一些控制播放，暂停的按钮在里面，手机中间有一个点，直视按钮2，3S就可以实现暂停播放,这是怎么实现的呢？

**Comment by Millertoken** [comment]
@ashqal 尴尬，还有一个请教的。如果我想在您的代码上面支持播放正常的视频，实现单双屏切换，请问需要修改些什么呢？（是否去掉把视频贴在球面上这个操作就可以？）看到3D播播这些做的很好，很想学习一下VR相关。

**Comment by ashqal** [comment]
@Millertoken 可以建个平面，把视频渲染到平面上就好了；单双屏已经实现了呀

**Comment by ashqal** [comment]
@Millertoken 已支持正常播放视频
