### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Maheshpurplenode** [ashqal/MD360Player4Android#194]
holding plus pointer at plugin logo more than five seconds, have to toast something

**Comment by ashqal** [comment]
```java
getVRLibrary().setEyePickChangedListener(new MDVRLibrary.IEyePickListener2() {
    @Override
    public void onHotspotHit(MDHitEvent hitEvent) {
        IMDHotspot hotspot = hitEvent.getHotspot();
        long hitTimestamp = hitEvent.getTimestamp();

        if (System.currentTimeMillis() - hitTimestamp > 5000){
            getVRLibrary().resetEyePick();
            // toast
        }
    }
});
```

**Comment by Maheshpurplenode** [comment]
sir i didn't mean this one. when holding plus pointer at plugin logo more than five seconds after that toast

**Comment by ashqal** [comment]
```java
getVRLibrary().setEyePickChangedListener(new MDVRLibrary.IEyePickListener2() {
    @Override
    public void onHotspotHit(MDHitEvent hitEvent) {
        IMDHotspot hotspot = hitEvent.getHotspot();
        long hitTimestamp = hitEvent.getTimestamp();

        // after five seconds
        if (System.currentTimeMillis() - hitTimestamp > 5000){
            getVRLibrary().resetEyePick();
            Toast.makeText(getContext(), "toast", Toast.LENGTH_SHORT).show();
        }
    }
});
```

**Comment by Maheshpurplenode** [comment]
hello sir sorry for the late reply. This method is under which class?

**Comment by mudin3i** [comment]
```
if (hotspot != null && hotspot.getTitle().equals("logo")) {
Toast.makeText(getApplicationContext(), "toast", Toast.LENGTH_SHORT).show();
}
```

add this after the line https://github.com/ashqal/MD360Player4Android/blob/03fa4e5e7b4cb7e1e8577f85224440ac0ff553d2/app/src/main/java/com/asha/md360player4android/MD360PlayerActivity.java#L383

**Comment by Maheshpurplenode** [comment]
thank you Mudin

**Comment by Maheshpurplenode** [comment]
Hi Mudin 
how to call next button click inside if statement
if (hotspot != null && hotspot.getTitle().equals("logo")) {
Toast.makeText(getApplicationContext(), "toast", Toast.LENGTH_SHORT).show();
}

**Comment by mudin3i** [comment]
If I were you, first, I would move ```getVRLibrary().setEyePickChangedListener``` into `BitmapPlayerActivity` and then make methods for loading next/preview photo and finally, call the methods `onHotspotHit`

**Comment by Maheshpurplenode** [comment]
Thank you Mudin, and i have one doubt how to add two logo (logo1,logo2) at a time left and right

**Comment by mudin3i** [comment]
It is pretty simple, make a method like below, and you will be able to add logos as much as you want:
```
void addLogoPlugin(MDPosition position, String tag, int logoResId){
        MDHotspotBuilder builder = MDHotspotBuilder.create(mImageLoadProvider)
                        .size(4f,4f)
                        .provider(activity, logoResId)
                        .tag(tag)
                        .position(position);
                MDAbsHotspot hotspot = new MDSimpleHotspot(builder);
                plugins.add(hotspot);
                getVRLibrary().addPlugin(hotspot);
}
```

in `onHotspotHit`, check hitHotspot's tag (for example, 'next', 'previous'), and call your methods (such as, next()/previous())

**Comment by Maheshpurplenode** [comment]
ok Mudin how to change logos positions left and right something like horizontally

**Comment by Maheshpurplenode** [comment]
ok fine, first spinner "CARDBOARD M&T" this method how to call a button click
