### ISSUE TITLE
Load image

### ISSUE THREAD

**Issue by christian160984** [ashqal/MD360Player4Android#2]
How can I load a spherical image with this library?

**Comment by ashqal** [comment]
The image is different from the video, but I will make it compatible in next release.

**Comment by ashqal** [comment]
For more info, See [BitmapPlayerActivity](https://github.com/ashqal/MD360Player4Android/tree/master/app/src/main/java/com/asha/md360player4android/BitmapPlayerActivity.java) in demo.
