### ISSUE TITLE
这个是不是改动了ijkplayer的代码

### ISSUE THREAD

**Issue by lijintan1990** [ashqal/MD360Player4Android#201]
ijkplayer有自己的渲染的代码，大神你是用你的代码替换了ijkplayer的渲染的代码吗，那你的libijkplayer.so和libijksdl.so是不是有改动？

**Comment by ashqal** [comment]
vrlib安卓版本没有替换ijk的渲染过程，
ijk提供了mediaplayer方式的实现，这种方式是把数据渲染到了surface上
