### ISSUE TITLE
getPlayer error

### ISSUE THREAD

**Issue by hungdev** [ashqal/MD360Player4Android#204]
hi everyone.i m facing problem with getPlayer like image. please help me to resolve this issues. thank you.

<img width="885" alt="screen shot 2017-12-06 at 11 33 53 am" src="https://user-images.githubusercontent.com/12009276/33644810-bb3e30c0-da79-11e7-9f3c-66067a62c1d7.png">

**Comment by ashqal** [comment]
```java
.build(findViewById(R.id.surface_view))
```
