### ISSUE TITLE
放大和缩小(pinch gesture)

### ISSUE THREAD

**Issue by jksfood** [ashqal/MD360Player4Android#21]
我通过ontouch事件，捕捉到了放大和缩小的手势，可是我该怎么利用您的库改变画面的尺寸？

**Comment by ashqal** [comment]
可能需要在写在库内部，MD360Director#updateProjectionNear，并且要处理下与Drag手势之间的冲突

**Comment by jksfood** [comment]
我将updateProjectionNear改为public权限，动态传值进去，我看log也有反应了啊，但是画面并没有发生改变。将near的值固定在代码里是有效果的，你原来的是0.7，我改成1.7后确实有效果，但为什么对动态改变的near值不相应呢？

**Comment by wuwenhu** [comment]
因为onTouch事件中没有捕捉到point事件, 在手势处理的控件TouchFixLinearLayout中onInterceptTouchEvent做个拦截就可以监听到所有point事件了, 目前onInterceptTouchEvent中做了个判断,DOWN事件中会返回false不拦截, 个人认为不管是视频进度还是添加音量/亮度/弹幕等功能, 全部在TouchFixLinearLayout的手势处理或者添加其他view就行了, glsurface不需要任何手势,所以父控件全部拦截应该没有任何影响,不知道作者会怎么考虑

**Comment by ashqal** [comment]
@wuwenhu 非常感谢，我上午也在整理这块代码，打算去掉库外面的一系列touch处理，库内部使用GestureDetector来处理点击

**Comment by ashqal** [comment]
https://github.com/ashqal/MD360Player4Android/commit/3acba03c8e699cb04d93dd9a62bf97c4344c8c4e

supported
