### ISSUE TITLE
TouchInput handling

### ISSUE THREAD

**Issue by AntonAFA** [ashqal/MD360Player4Android#212]
Hello, I have some issue with handling of the TouchInput on the GLSurfaceView which is passed into the MDLibrary. 
As I see the touch input is handled inside the MD library (MDTouchHelper -> handleTouchEvent() -> return true) and never released to the application. 
Is there any convenient way to add Touch/Click listener on the GLSurfaceView in order to be capable perform actions when user input is detected on it? Like show/hide Play/Pause button when surface touched.

**Comment by ashqal** [comment]
https://github.com/ashqal/MD360Player4Android/wiki/Advanced-Usage#click-listener

```java
@Override
protected MDVRLibrary createVRLibrary() {
    return MDVRLibrary.with(this)
            .....
            .listenGesture(new MDVRLibrary.IGestureListener() {
                @Override
                public void onClick(MotionEvent e) {
                    //....
                }
            })
            .build(R.id.surface_view);
}
```
