### ISSUE TITLE
MD360VideoPlayerActivity Error Loading Video

### ISSUE THREAD

**Issue by wahyouwebid** [ashqal/MD360Player4Android#222]
Hallo
Thanks for Beautiful Library

i have a problem with VideoPlayerActivity every time i load the video from another source like http url. 
example url link:
https://video.360cities.net/davilla/01588188_sa27-1920x960.mp4

its show an error message what = -10.000 extra =0. what does it means ? 

thank you master

**Comment by HyowonHwang** [comment]
The player you tested would not support https protocols or your media file is invalid

**Comment by wahyouwebid** [comment]
problem solve master thanks
