### ISSUE TITLE
I can not play online video

### ISSUE THREAD

**Issue by Thanhktm** [ashqal/MD360Player4Android#224]
Try this: http://d8d913s460fub.cloudfront.net/krpanocloud/video/airpano/video-1920x960a.mp4

**Comment by ashqal** [comment]
The http protocol will be upgrade to https on this website, which the ijk player do not support by default.
For more information, https://github.com/Bilibili/ijkplayer/issues/2433

Or, using `AndroidMediaPlayer` instead of `IjkMediaPlayer` in `MediaPlayerWrapper.java`
```java
mPlayer = new AndroidMediaPlayer();
```
