### ISSUE TITLE
Set up start x position

### ISSUE THREAD

**Issue by HyowonHwang** [ashqal/MD360Player4Android#227]
I wonder if I can set up start x(yaw) position with your beautiful library. 
Please, let kindly let me know how to do it.

**Comment by HyowonHwang** [comment]
Hi, I found the way how this do with direction builder, thx

**Comment by iantomemortel** [comment]
@HyowonHwang, how were you able to accomplish this? My problem is how to I override the x, y, z to zero, because I'd like to have a reset button.
