### ISSUE TITLE
部分手机显示绿屏

### ISSUE THREAD

**Issue by 54fellow** [ashqal/MD360Player4Android#23]
这个魅蓝metal播放vr视频，会显示绿色，请问是什么原因呢
![qq 20160506175804](https://cloud.githubusercontent.com/assets/17311765/15070019/3484b0be-13b4-11e6-8176-f7abe81dd99e.jpg)

**Comment by ashqal** [comment]
试过魅蓝note1没问题，手头没有魅蓝metal不能重现。请问放所有视频都是这个情况吗？你把MediaPlayerWrapper.java

``` java
mPlayer = new IjkMediaPlayer();
```

改成

``` java
mPlayer = new AndroidMediaPlayer();
```

试试

**Comment by 54fellow** [comment]
测的几个视频都有该问题，放http://recorded.live.doubo.tv/realrealcomp.mp4的时候，用IjkMediaPlayer前几秒会有绿色闪烁，后面就好了，用AndroidMediaPlayer在后面还会不时闪烁。是否可以设置刷新率或者编码调整呢？我用ijkplayer中的demo播放视频是正常的

**Comment by yiwuxue** [comment]
vivo x6d也有绿屏的问题

**Comment by 54fellow** [comment]
注释player.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);就好了
