### ISSUE TITLE
魅族手机问题

### ISSUE THREAD

**Issue by Millertoken** [ashqal/MD360Player4Android#24]
我发现在魅族手机上，画面没办法跟随手机动，我抓了sensor的回调，发现魅族根本没有这个传感器的回调。而且在部分手机上很晃。

**Comment by ashqal** [comment]
可以提供下机型吗？我手头上有魅族mx3和魅蓝note1

**Comment by Millertoken** [comment]
@ashqal MX4不行，还有一台魅蓝的，什么型号我不知道。三星的S6移动的时候很晃

**Comment by ashqal** [comment]
http://bbs.flyme.cn/thread-121515-1-1.html
mx4pro反馈比较多，好像没看到mx4的反馈

**Comment by Millertoken** [comment]
@ashqal 我看你是使用的旋转角度传感器，这个传感器的值是4位数组，传给opengl的是个16位的数据。我后面想换陀螺仪传感器，但是陀螺仪只有三位数组数据，我应该如何转换成16位数据呢？opengl只接收16位数组么？

**Comment by Millertoken** [comment]
@ashqal 陀螺仪

**Comment by Millertoken** [comment]
@ashqal 我试了好几个机器，旋转角度传感器还是问题很多，能否考虑使用陀螺仪传感器这些来实现？

**Comment by ashqal** [comment]
1.陀螺仪传出来的是角速度，不是当前状态
2.就算记录初始值，然后按照角速度算出偏移量，时间一长肯定会有误差
3.初始值不一定正好是正视角度，这个又需要用户去调节
4.旋转矢量传感器是最合适的，iOS版本也是用的这个值，而且是系统sdk提供的
