### ISSUE TITLE
和新版本vlc一起工作时无法显示画面，只有声音。

### ISSUE THREAD

**Issue by sek790c** [ashqal/MD360Player4Android#248]
项目需要，在vlc的基础上二次开发。
build.gradle
releaseApi "org.videolan.android:libvlc-all:3.3.0-eap10"
但是按照https://github.com/mrmaffen/vlc-android-sdk给的sample去写，只有声音，没有画面。不知道是参数设置有问题还是vlc没有向前兼容呢

**Comment by yougaohui** [comment]
1、
options.add("--vout=android-display");
libvlc = new LibVLC(this,options);
2、
 public void vlcSetSurface(Surface surface){
        // Set up video output
        final IVLCVout vout = mMediaPlayer.getVLCVout();
        vout.setVideoSurface(surface, null);
        //vout.setSubtitlesView(mSurfaceSubtitles);
        vout.addCallback(this);
        vout.attachViews(new IVLCVout.OnNewVideoLayoutListener() {
            @Override
            public void onNewVideoLayout(IVLCVout vlcVout, int width, int height, int visibleWidth, int visibleHeight, int sarNum, int sarDen) {

            }
        });
    }
这样做就可以了，亲测可用

**Comment by ashqal** [comment]
楼上优秀

**Comment by sek790c** [comment]
2楼牛逼，vlc的维护者回复2.5之后的版本不支持外部渲染，eglcontext导致的

**Comment by DevinCGB** [comment]
2楼牛逼
