### ISSUE TITLE
请问，外接HID通信眼镜设备，怎么使用眼镜四元数 数据，来做全景，而不是使用手机的陀螺仪

### ISSUE THREAD

**Issue by zgmd** [ashqal/MD360Player4Android#254]

**Comment by ashqal** [comment]
1 如何自定义外部数据输入？
可以参考`MotionStrategy`实现`AbsInteractiveStrategy`，然后在外部注入给库使用
https://github.com/ashqal/MD360Player4Android/blob/dev-m251/vrlib/src/main/java/com/asha/vrlib/strategy/interactive/MotionStrategy.java

2 如何把四元组转成旋转矩阵matrix？
`MDQuaternion#toMatrix`
https://github.com/ashqal/MD360Player4Android/blob/dev-m251/vrlib/src/main/java/com/asha/vrlib/model/MDQuaternion.java

**Comment by zgmd** [comment]
感谢
