### ISSUE TITLE
陀螺仪转动的时候，图像会变形扭曲

### ISSUE THREAD

**Issue by aixiaoyi123** [ashqal/MD360Player4Android#27]

**Comment by aixiaoyi123** [comment]
![Uploading device-2016-05-12-165359.jpg…]()

**Comment by ashqal** [comment]
请问有截图吗？

**Comment by aixiaoyi123** [comment]
![device-2016-05-12-165359](https://cloud.githubusercontent.com/assets/7221622/15209543/2f5808ca-1864-11e6-87b0-37bcc1b0318f.jpg)

**Comment by aixiaoyi123** [comment]
操作方式，往右斜角度转，几乎都是变形的

**Comment by aixiaoyi123** [comment]
在安卓5.1.1系统，4.4系统不会有这个问题

**Comment by ashqal** [comment]
4.4上的截图可以发一下吗？

**Comment by aixiaoyi123** [comment]
![device-2016-05-12-171337](https://cloud.githubusercontent.com/assets/7221622/15209763/92cf65a0-1865-11e6-9922-ba9fc8050727.jpg)

**Comment by aixiaoyi123** [comment]
![device-2016-05-12-171809](https://cloud.githubusercontent.com/assets/7221622/15212848/c1f374f6-1875-11e6-932a-e2851aa3ad3f.jpg)

**Comment by ashqal** [comment]
感谢反馈，看着是有点问题，我周末跟进一下

**Comment by huyn** [comment]
红米 note 2
Android版本 5.0.2
motion模式下向左/右转也会存在这个问题
touch模式下ok

**Comment by huyn** [comment]
补充一下，版本1.5.3

**Comment by ashqal** [comment]
http://v.youku.com/v_show/id_XMTY1OTEyNjg5Mg==.html

**Comment by ashqal** [comment]
#84
