### ISSUE TITLE
How to add projection mode?

### ISSUE THREAD

**Issue by tiepviet** [ashqal/MD360Player4Android#3]
Sorry for inconvenience.

I want to create projection mode when playing 360 degree video. 
- Perspective
- Orthographic
- LittlePlanet
- Round

@ashqal  Could you help me? Thank you so much.

**Comment by ashqal** [comment]
Sorry, I can't get your point. Would you please provide more information?

**Comment by tiepviet** [comment]
I'm so sorry. I want to make more features. 
Ex: http://hugin.sourceforge.net/docs/manual/Panorama_formats.html#Equirectangular
http://www.ptgui.com/ptguihelp/projections.htm

**Comment by tiepviet** [comment]
Thank you so much.

**Comment by tiepviet** [comment]
@ashqal Sorry for convenience.
https://github.com/ashqal/MD360Player4Android/blob/master/vrlib/src/main/java/com/asha/vrlib/MD360Director.java
In above code, you used `Matrix.frustumM` to update projection. And I tried replacing with `Matrix.perspectiveM` and `Matrix.orthoM` but it didn't work. I'm a very very beginner openGL. Can you help me?

**Comment by ashqal** [comment]
matrixProjection.zip:   [WIN](http://www.songho.ca/opengl/files/matrixProjection.zip) or [OS X 10.6+](http://www.songho.ca/opengl/files/matrixProjection_mac.zip) may help.

**Comment by tiepviet** [comment]
@ashqal I understood matrix projection. But I'm having  a problem with model position. I had a bit iOS code about this problem . I want to change it to android but I never do android before. Can you explain for me? I am very grateful to you

**Comment by ashqal** [comment]
It seems the modelPosition is (x,y,z), the original model position is (0,0,0)

**Comment by ashqal** [comment]
Sorry, this feature may delay. Because it is  totally different from the current way of renderer. For example , the [`LittlePlanet`](http://krpano.com/krpano.html?pano=panos/balkon/balkon.xml&view.stereographic=true&view.fisheye=1.0&view.fov=143&view.fovmax=150&view.hlookat=190&view.vlookat=70) combine six pieces of face into a scene. I need to  spend more time on understanding the theory.
