### ISSUE TITLE
进入触摸模式以后似乎视角偏右了一些角度

### ISSUE THREAD

**Issue by fangyong** [ashqal/MD360Player4Android#31]
使用touch模式或者reset以后初始化位置在偏右侧位置，请问如何修改使它初始化位置在比较正的位置？

**Comment by ashqal** [comment]
是不是错觉？我没调整初始化位置

**Comment by fangyong** [comment]
比如这个视频，原本文字是对着正中的，
![qq20160516-1](https://cloud.githubusercontent.com/assets/2127319/15281015/ce6d6394-1b69-11e6-9a8f-1899cf99174e.png)
这是用utovr播放的效果
![qq20160516-2](https://cloud.githubusercontent.com/assets/2127319/15281038/14f2fcca-1b6a-11e6-9095-2a95e59c6fa0.png)
视频连接地址是：http://cache.utovr.com/201508270528174780.m3u8
ps.似乎在你git上另一个项目中是正常的https://github.com/AndroidForks/MD360Player4Android

不知道初始化位置是如何设置的，方便的话可否提供一下思路？

**Comment by ashqal** [comment]
在`MD360Director`中修改`mAngle`值，最新版本提供了自定义`MD360DirectorFactory`，
你可以这么做：

``` java
@Override
protected MDVRLibrary createVRLibrary() {
    return MDVRLibrary.with(this)
            ...
            .directorFactory(new DirectorFactory()) //替换默认MD360DirectorFactory
            ...
            .build(R.id.surface_view1,R.id.surface_view2);
}

private static class DirectorFactory extends MD360DirectorFactory{
    @Override
    public MD360Director createDirector(int index) {
        // angle to rotate in degrees
        // setAngle
        switch (index){
            case 1:   return MD360Director.builder().setAngle(20).setEyeX(-2.0f).setLookX(-2.0f).build();
            default:  return MD360Director.builder().setAngle(20).build();
        }
    }
}
```

**Comment by fangyong** [comment]
非常感谢，我试试看！

**Comment by fangyong** [comment]
经测试，大概逆时针旋转90度就正了，谢谢指点！

**Comment by ashqal** [comment]
赞
