### ISSUE TITLE
如何获取当前视野中心位置的坐标呢？

### ISSUE THREAD

**Issue by fangyong** [ashqal/MD360Player4Android#37]
实在不好意思，我研究了半天没有研究出来，只好厚着脸皮又来请教你了。
请问如何获取到当前视野中心位置在视频中的坐标呢？？
还有个问题就是，如果我想渲染一个水印到视野中的某一个位置，有办法实现么？

**Comment by ashqal** [comment]
这个库是对3d球进行旋转，实现渲染不同可视区域的，所有的旋转操作由`MD360Director`的`mModelMatrix`完成；

假设初始点位置为(0,0,-1)，把(0,0,-1)作为一个三维列向量，去乘以一个三维段矩阵（`MD360Director#shot`中的`mModelMatrix`四维矩阵去掉最后一行一列），得到的三维行向量就是新的(x,y,z)坐标。

**Comment by ashqal** [comment]
水印的话不如先直接盖在二维的View上算了。如果要加到三维世界中，还是比较麻烦的。因为如果你是以平面方式加进去，不同角度看变形会比较严重

**Comment by fangyong** [comment]
非常非常感谢你的耐心回答！感觉听你解释以后清晰多了！
