### ISSUE TITLE
如何设置初始画面的方向

### ISSUE THREAD

**Issue by reaper12** [ashqal/MD360Player4Android#40]
如何设置初始画面的方向？比如初始画面是这个
![screenshot_2016-05-23-16-25-24_com smax eschervr](https://cloud.githubusercontent.com/assets/13657190/15464657/2feb8b5c-2103-11e6-81f4-14376001eaaa.png)
我想向右平移一点：
![screenshot_2016-05-23-16-25-19_com smax eschervr](https://cloud.githubusercontent.com/assets/13657190/15464688/49d7fb18-2103-11e6-8a4d-e20eb479efec.png)

**Comment by ashqal** [comment]
#31

**Comment by reaper12** [comment]
多谢

**Comment by apsylone** [comment]
How to do this with the 2.x version ?
The "setAngle" method for MD360Director doesn't exists anymore :-/
