### ISSUE TITLE
惯性滑动

### ISSUE THREAD

**Issue by wuwenhu** [ashqal/MD360Player4Android#41]
你好, 我在Demo里添加了惯性滑动, 这是参考 https://github.com/pangff/DemoView/blob/v2/DemoView/src/com/pangff/demoview/MyView.java

希望大神能直接加到库里,谢谢

**Comment by ashqal** [comment]
46abeb72624b33b0d750f9679a1cfc6bf23913ae
已通过`onFling`方式支持，感谢！
