### ISSUE TITLE
能不能每次打开视频的时候都固定一个方向？

### ISSUE THREAD

**Issue by reaper12** [ashqal/MD360Player4Android#42]
能不能每次打开视频的时候都固定一个方向？比如我现在对着正前方打开视频的话是一个画面，如果对着正南方打开的话又是另一个画面，而我想实现每次打开视频，不管是对着哪个方向打开的时候都是同一个初始画面

**Comment by wuwenhu** [comment]
初始化时touch模式就行

**Comment by reaper12** [comment]
但我依然想用陀螺仪

**Comment by reaper12** [comment]
因为视频一打开视频会显示标题，想手机放入设备后播放每次打开视频的时候都正对着这个标题

**Comment by reaper12** [comment]
应该是每次打开X的位置都一样

**Comment by wuwenhu** [comment]
目测要在MotionStrategy中设置矩阵初始值, 在update时先计算,这是我的看法,然而我矩阵知识惨不忍睹,不知道我的想法是不是对的```

**Comment by reaper12** [comment]
我也是这样想的，但现在是偏移量不知道怎么算 ，我的矩阵知识也不行

**Comment by reaper12** [comment]
@ashqal 请大神给点指导意见

**Comment by ashqal** [comment]
@reaper12 我线代也是烂的不行，sensor数据出来已经是矩阵了，感觉比较麻烦，成本>需要的效果，暂不实现

**Comment by reaper12** [comment]
其实我觉得这并不是成本>需要的效果的问题，而是一种用户体验。想象一下，如果有一段演唱会的VR视频，用户肯定希望一打开视频第一眼看到的是舞台的方向，而不是出口大门的方向。

**Comment by ashqal** [comment]
@reaper12 用户只要找准一个方向就可以了，而且这样所有人都可以统一一个方向。一般玩vr都会有一个比较大的空间，所以无伤大雅

**Comment by ashqal** [comment]
``` java
MDVRLibrary.INTERACTIVE_MODE_CARDBORAD_MOTION
MDVRLibrary.INTERACTIVE_MODE_CARDBORAD_MOTION_WITH_TOUCH
```
