### ISSUE TITLE
How to get an event when video playback finishes?

### ISSUE THREAD

**Issue by fabiotnt** [ashqal/MD360Player4Android#43]
How I implement a equivalent listener to - (void)videoPlayerViewDidReachEnd:(VIMVideoPlayer *)videoPlayer on iOS version in my Android App?

I have tried to get a message from onDestroy event, but when videoplayback stop, this method don't is fired.

Thanks

**Comment by ashqal** [comment]
`MediaPlayer.OnCompletionListener` 
http://stackoverflow.com/questions/9962998/oncompletion-listener-with-mediaplayer
Is that what you want?

**Comment by fabiotnt** [comment]
I think yes. Thanks a lot.
