### ISSUE TITLE
Does this support youtube player

### ISSUE THREAD

**Issue by shivanig30** [ashqal/MD360Player4Android#44]
I want to run also the YouTube 360 videos .
Does this player runs the YouTube videos.

**Comment by ashqal** [comment]
Do you have any URL of YouTube 360 video stream?

**Comment by shivanig30** [comment]
https://www.youtube.com/watch?v=aQd41nbQM-U 

The above is URL of YouTube 360 video stream. Please do check it whether URL works in the MD360Player.

**Comment by ashqal** [comment]
Sorry, the answer is NO.
