### ISSUE TITLE
导入微博sdk后，播放出错

### ISSUE THREAD

**Issue by jksfood** [ashqal/MD360Player4Android#47]
你好，我发现个问题，搞了好久没有解决，我在集成微博第三方登录后，发现部分机子无法播放视频，像是华为meat7,Lg5等等，但有的机子能够正常播放。我比较了一下，发现，可能是s0库的问题，因为在我集成的sdk当中，只有微博SDK和ijkplayer用到了so库，当我删掉微博SDK库后，播放器又能够正常适配所有的机器播放了。搞不懂这是为什么？

我早gradle中加了这句：compile 'com.github.8tory:weibo-android-sdk:-SNAPSHOT'

然后就不能播放了 。

报错信息：
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-weibo-android-sdk-core-3.1.4_cb5be235648f20ce3dae1eb49c702704e22e7382-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-java-0.4.5_301e583e7006e65bfc439fc6de23b8c7a5e386e2-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-armv7a-0.4.5_16eab7ffae67c1cb5f7e787ccce9e5b0e0835114-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-support-annotations-23.2.0_2aa979df686c6cddf3e3cb3dc08b5f0c749828c3-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-picasso-2.5.2_efef3d5c78b95624ad3d185370992dbdbf36bc0f-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-internal_impl-23.2.0_d2eef739ef69f25e181879b8aef75fab610a6eeb-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-com.infstory-weibo-android-sdk-core-3.1.4_3e8ee89e2d5b97459af1553da1dde348ba425cb0-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-com.github.8tory-weibo-android-sdk--SNAPSHOT_f63c85d600c0c0046e1088c84580b19bc765ec1a-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.2.0_2592da3b32e21b8d2aec3778e0677295154e8ed9-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-com.android.support-support-v4-23.2.0_0e62e90d2810375ef464a49fec4fac2b42a27f26-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.2.0_6f636057addae73c4003267e4fe8ac807e0916ae-classes.dex", dex file "/data/data/com.asha.md360player4android/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-23.2.0_19d4813e91635ba991c5fac9feb3277a7d4f3720-classes.dex"],nativeLibraryDirectories=[/data/app/com.asha.md360player4android-1/lib/arm64, /data/app/com.asha.md360player4android-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
                                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                           at java.lang.System.loadLibrary(System.java:1076)
                                                                                           at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                                                           at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
                                                                                           at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:209)
                                                                                           at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:205)
                                                                                           at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:196)
                                                                                           at com.asha.md360player4android.MediaPlayerWrapper.init(MediaPlayerWrapper.java:33)
                                                                                        at com

**Comment by ashqal** [comment]
``` java
defaultConfig {
    minSdkVersion 16
    targetSdkVersion 22
    versionCode 11
    versionName "1.1.3"
    ndk {
        //设置支持的SO库架构
        abiFilters 'armeabi-v7a' //,'armeabi', 'x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
    }
}
```

**Comment by jksfood** [comment]
可以  谢谢
