### ISSUE TITLE
Dome Video Support

### ISSUE THREAD

**Issue by liuxue0905** [ashqal/MD360Player4Android#49]
你好：
您的渲染库中有支持dome半球视频的部分代码，渲染是没问题的。但是初始的位置是不完美的，拖动时的方式也暂未处理。
请问今后是否会对这部分功能进行完善？

**Comment by ashqal** [comment]
可以发我一个dome的视频吗

**Comment by liuxue0905** [comment]
@ashqal 
你好：
半球视频稍后发到您邮箱中。
使用vrlib中的MDDome3D类，可以播放。
其中的问题有：
1.MDDome3D内部的object，是通过加载obj文件生成的，这个obj里面的半球并不太圆。所以还是您在360中写过的全球比较圆。
2.陀螺仪或Touch的交互不太完美

**Comment by liuxue0905** [comment]
@ashqal MDDome3D不是特别圆的原因可能是：视频尺寸不是正方形，尽管视频中心是圆的。纹理映射时，是映射的整个视频大小。

**Comment by ashqal** [comment]
有没有可以完美渲染的参考app？
最新准备攻克这个，麻烦发我一下，谢谢

**Comment by ashqal** [comment]
麻烦试一下交互上这样ok吗？

``` java
compile 'com.github.ashqal:MD360Player4Android:0f4dc97ebb'
```

``` java
@Override
protected MDVRLibrary createVRLibrary() {
    return MDVRLibrary.with(this)
            ...
            .displayAsDome() //default is displayAsShpere()
            ...
            .build(R.id.surface_view);
}
```
