### ISSUE TITLE
Problem in Rotate 

### ISSUE THREAD

**Issue by sinaone1** [ashqal/MD360Player4Android#5]
Hi
I have Sony Xperia Z
When i test your demo then video automatic rotate in a point around itself (I think there is a little problem in 360 degree)
![screenshot_2016-04-14-11-04-26](https://cloud.githubusercontent.com/assets/11288019/14518988/0e11c78a-0231-11e6-9a02-6bc8beaf2364.png)
Please fix this bug.
thank you.

**Comment by ashqal** [comment]
Reproduce every time?

**Comment by sinaone1** [comment]
Yes, it's every time

**Comment by ashqal** [comment]
Would you please install [this app](https://play.google.com/store/apps/details?id=kr.sira.compass&hl=zh_CN) and test if it worked well on your mobile? And what's your android system version? Thank you very much.

**Comment by sinaone1** [comment]
My android system version is 5.1.1
I've tested it and yes it works fine.

**Comment by martinbuezas** [comment]
I have the same issue, but my gyroscope is not working fine, even after trying everything out there to calibrate. Yet, somehow cardboard's SDK controller sample manages to work fine with no jumps in rotation. I'm trying to figure out what is they are doing different but maybe a look from someone with more knowledge in projections would help this fix.

**Comment by ashqal** [comment]
@sinaone1 still has this bug now?

**Comment by matejvida** [comment]
Yes, this is still happening on multiple phones that we have here. I looks like the sensor data overflows or something, than the video rotates and after that is works fine. This happens every time when you make a full 360 circle on the x axis.
