### ISSUE TITLE
process

### ISSUE THREAD

**Issue by jksfood** [ashqal/MD360Player4Android#50]
<activity
            android:name=".VideoPlayerActivity"
            android:configChanges="screenSize|orientation"
            android:label="MDMultiDemoActivity"
            android:screenOrientation="landscape"
            android:process=":vrPlayer"
            />
这里为什么要加android:process=":vrPlayer"，有什么作用吗？加了这句后，我在页面上存的值有些会返回空。

**Comment by ashqal** [comment]
可以去掉，意思是这个Activity在新起的vrPlayer进程打开

**Comment by jksfood** [comment]
好的
