### ISSUE TITLE
陀螺仪出现晃动比较严重的情况

### ISSUE THREAD

**Issue by reaper12** [ashqal/MD360Player4Android#52]
陀螺仪出现晃动比较严重的情况，特别是定点之后进行移动的时候，会出现上下晃动

**Comment by reaper12** [comment]
特别是在三星note5上，不知是不是手机分辨率过大的问题

**Comment by ashqal** [comment]
1.3版本调高了默认的sensor更新频率

**Comment by reaper12** [comment]
sensor更新频率指的是设置SensorManager.SENSOR_DELAY_GAME这些吗？

**Comment by ashqal** [comment]
@reaper12 是的 你看看这个是不是有影响

**Comment by reaper12** [comment]
不是  是都设置过了  会出现像半瓶水那样的晃动，特别是在移动之后停下，或者是定位之后移动

**Comment by reaper12** [comment]
感觉像Z轴旋转有延迟一样

**Comment by reaper12** [comment]
这个问题在双屏模式下比较严重，是不是在双屏下陀螺仪矩阵的获取没有做适配

**Comment by ashqal** [comment]
@reaper12 双屏和单屏旋转矩阵获取没有区别

**Comment by ashqal** [comment]
Please try

``` java
MDVRLibrary.INTERACTIVE_MODE_CARDBORAD_MOTION
```
