### ISSUE TITLE
低api版本的设备有适配的方法么？

### ISSUE THREAD

**Issue by fangyong** [ashqal/MD360Player4Android#53]
手头碰巧有一部api版本15的设备，有对它适配的可能么？

**Comment by ashqal** [comment]
双屏功能使用了一个api16的函数，如果剥离双屏显示，可以支持到api15（最低了，再低就不支持opengles2.0了）

现在api15的机子非常少，配置肯定也很差，还是放弃吧...

**Comment by fangyong** [comment]
你好，我现在就是单屏显示的，并且可以支持到15就可以了，我需要如何修改进行适配呢？

**Comment by ashqal** [comment]
可能有点复杂 我可以帮你适配下 这个需求我今天晚上就可以帮你搞定

**Comment by fangyong** [comment]
那真的要麻烦你了！恩人啊1~

**Comment by ashqal** [comment]
提交了，可以用`-SNAPSHOT`试一下

**Comment by ashqal** [comment]
82a5340d0699428a2d28c196d36db14719faa6b7

**Comment by fangyong** [comment]
非常感谢，我试试看

**Comment by fangyong** [comment]
你好，不好意思，再打扰一下，使用了你的最新代码成功地把项目跑在api15的设备上了，但是画面非常卡顿，尝试直接用videoview直接播放全景视频播放成平面的则非常流畅，这种情况是不是表示这个设备过于老旧，已经没法支持全景播放了？应该也没有什么优化空间了吧？如果这样的话就只能宣布放弃这个设备的支持了！

**Comment by ashqal** [comment]
`MediaPlayerWrapper`里

``` java
mPlayer = new IjkMediaPlayer();
```

换成

``` java
mPlayer = new AndroidMediaPlayer();
```

试试

**Comment by fangyong** [comment]
嗯~换完依然卡~甚至还不如IjkMediaPlayer的效果好

**Comment by ashqal** [comment]
那没办法了

**Comment by fangyong** [comment]
非常感谢，确认它不行了，我就放弃它了
