### ISSUE TITLE
cannot play video properly

### ISSUE THREAD

**Issue by s9iper1** [ashqal/MD360Player4Android#54]
i am not be able to play video the sound stream is fine but video got stuck in the middle. 
i am not be able to understand the issue.

**Comment by ashqal** [comment]
Sorry, I need more details.

**Comment by s9iper1** [comment]
what you need from me ? i already sent email to you.

**Comment by ashqal** [comment]
1.How do you use this library?
2.What is your video format? Is that a 4k video?
3.What device do you use?

**Comment by s9iper1** [comment]
i have imported your whole project as a module via project structure -> +
-> import gradle project.
mp4 yes it is a 4K video dimensions 4000x2000
device is android one

**Comment by ashqal** [comment]
Does the android one support 4k video? Please try to play the video in other player.
