### ISSUE TITLE
HTTPS video not playing

### ISSUE THREAD

**Issue by terenzeyuen** [ashqal/MD360Player4Android#56]
Can't seem to play HTTPS url..

**Comment by ashqal** [comment]
https://github.com/Bilibili/ijkplayer/issues/1269
As bbcallen said,
You should build FFmpeg with OpenSSL support.

**Comment by terenzeyuen** [comment]
Is that the video encoding? So I can tell the video provider..

**Comment by ashqal** [comment]
No, the ijkplayer is using ffmpeg(in .so file). By default, the https scheme can't recognized by ffmepg without OpenSSL. So you should compile a new .so file which has https option.

**Comment by RamIndani** [comment]
Will it be fine with MediaPlayer or ExoPlayer with HTTPS url's. or m3u8 
Edit: I was able to use it successfully with HTTPS m3u8 streaming using ExoPlayer

**Comment by ashqal** [comment]
@RamIndani 
I think the answer is YES.
The ONLY one step you should do is setting the surface(created from MDVRLibrary#asVideo callback) to player.

``` java
player.blockingSendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surface);
```

**Comment by RamIndani** [comment]
@ashqal Thank you for confirming, I was able to run it successfully and I updated my question accordingly so that others will find it helpful and I simply used setSurface of ExoPlayer and it worked.

**Comment by ashqal** [comment]
@RamIndani nice!

**Comment by debrajb** [comment]
How to load video from phone internal memory?

**Comment by sharmadev2506** [comment]
You need to replace HTTPS to HTTP,  after that it will run successfully. Although this is just a way around for some time, it may help.  Anyone with the real solution please post it here or it would be better to improve the library.
