### ISSUE TITLE
播放普通视频的问题

### ISSUE THREAD

**Issue by xm007forgithub** [ashqal/MD360Player4Android#57]
请教一下怎么播放普通的非全景视频啊，现在这种会扭曲的不叫样子，我也是最近才转Vr这块的

**Comment by ashqal** [comment]
非全景的视频直接用ijk放就可以了

**Comment by xm007forgithub** [comment]
另外还有一个问题麻烦一下 怎么区别一个视频是不是全景视频啊

**Comment by ashqal** [comment]
没办法区别

**Comment by xm007forgithub** [comment]
真是一个悲伤的故事

**Comment by ashqal** [comment]
视频流过来只知道是一个普通的视频，只是渲染的时候做了一些处理，所以这个没办法区分，让用户手动设置吧
