### ISSUE TITLE
Video is moving after i stop

### ISSUE THREAD

**Issue by s9iper1** [ashqal/MD360Player4Android#58]
when i move around the video rotate this is normal behavior but when i stop the video is still moving itself.

**Comment by ashqal** [comment]
I think it is correct.

**Comment by s9iper1** [comment]
but if i want to stop the video rotation when i stop how can i do that ? 
i donot want the video to move after i stop.
i think its auto adjust the video according to rotation.

**Comment by ashqal** [comment]
You may call

``` java
mInteractiveModeManager.onPause(context);
```

to pause the sensor or touch, and

``` java
mInteractiveModeManager.onResume(context);
```

to resume the sensor tor touch in `MDVRLibrary.java`.

**Comment by s9iper1** [comment]
let me explain you my whole issue.
this code is already in there
i am loading video from internet and due to low internet speed its buffering so when i shake my mobile during buffering and stop the mobile than the video is still in motion. let me show you a video of it.
here is the video where you can see when i stop moving phone the video is still adjusting or moving.
https://goo.gl/hypF25

**Comment by ashqal** [comment]
Ok, I will check it later.

**Comment by ashqal** [comment]
Thanks to the Great Fire Wall, 
Could you send it via email please?

**Comment by s9iper1** [comment]
ok i am sending these details on your email. also i am making another video that will show this more and more clearly.
thanks.

**Comment by ashqal** [comment]
It's funny,
and I think it is `Buffering => Play => Buffering => Play` make the movie moving but not the motion sensor.

You can listen to the buffering status of MediaPlayer, such as:

``` java
mp.setOnInfoListener(new OnInfoListener() {

    @Override
    public boolean onInfo(MediaPlayer mp, int what, int extra) {
        switch (what) {
            case MediaPlayer.MEDIA_INFO_BUFFERING_START:
                loadingDialog.setVisibility(View.VISIBLE);
                break;
            case MediaPlayer.MEDIA_INFO_BUFFERING_END:
                loadingDialog.setVisibility(View.GONE);
                break;
        }
        return false;
    }
});
```

reference:[Android - How to tell when MediaPlayer is buffering](http://stackoverflow.com/questions/4465494/android-how-to-tell-when-mediaplayer-is-buffering)

**Comment by s9iper1** [comment]
thanks alot you helped alot. and can i enable the buffering while the video
is paused ?

**Comment by ashqal** [comment]
I don't know such detail of `MediaPlayer`, and this library is focus on the renderer not the player.
https://github.com/Bilibili/ijkplayer
https://developer.android.com/reference/android/media/MediaPlayer.html
may help.

**Comment by s9iper1** [comment]
alright thanks alot. :)
