### ISSUE TITLE
底部会出现图形扭曲的情况(image distortion)

### ISSUE THREAD

**Issue by reaper12** [ashqal/MD360Player4Android#6]
视频底部会出现图形扭曲的情况，如果使用cardboard就不会出现

**Comment by reaper12** [comment]
![screenshot_2016-04-14-12-47-41_com smax eschervr](https://cloud.githubusercontent.com/assets/13657190/14525411/e4657230-026f-11e6-8827-235d1a028f16.png)
这张用的您的lib,最底部的文字已经出现了扭曲

![screenshot_2016-04-14-13-12-22_com smax eschervr](https://cloud.githubusercontent.com/assets/13657190/14525394/caf5de02-026f-11e6-8cd9-7a2379171ef1.png)
这张用的是cardborad SDK

**Comment by ashqal** [comment]
可以提供一下能重现类似问题的视频吗？

**Comment by reaper12** [comment]
http://aivr.ynhdkc.com/Uploads/Download/2016-04-07/570624aae1c52.mp4  这是下载地址
还有请问一下  怎么实现画面的放大缩小，类似于镜头的拉近拉远？

**Comment by ashqal** [comment]
多谢，`MD360Director#updateProjectionNear`，near变大就可以了

**Comment by reaper12** [comment]
早上好！updateProjectionNear是个私有方法，我要如何去调用?

**Comment by ashqal** [comment]
哈哈 早上好 因为原来想法是Pinch手势控制缩放，外面传了touch事件到VRLib里，库内部就能处理掉这个缩放，所以我就先把这个方法private了。

你可以开个新issue 我周末可以实现一下

**Comment by jksfood** [comment]
不是很懂，这个手势控制缩放的功能实现了吗？为什么那个方法还是private的？

**Comment by ashqal** [comment]
Pinch手势估计得M1-2了，请跟踪#10 How to zoom with pinch?

**Comment by Millertoken** [comment]
@ashqal 我也想问下，我这边也遇到了那个图标扭曲的问题，请问这个问题解决了么。谢谢。

**Comment by ashqal** [comment]
暂时没有解决，网上也有很多类似的讨论，没找到合适的解决方法
[textured-spheres-without-strong-distortion](http://stackoverflow.com/questions/213147/textured-spheres-without-strong-distortion)，[polar-coordinate-distorted-textures](https://hub.jmonkeyengine.org/t/polar-coordinate-distorted-textures/3782)，[360-display-in-unity-w-blender](http://horriblepain.com/2015/05/360-display-in-unity-w-blender/)

**Comment by reaper12** [comment]
cardboard可以借助于Rajawali来实现VR视频播放的，https://github.com/Rajawali/Rajawali
一个简单的例子https://github.com/SMalpica/RajawaliSampleProject

**Comment by Millertoken** [comment]
@ashqal 好的。我也抽空学习学习。感谢回复。

**Comment by ashqal** [comment]
@reaper12 Rajawali像是一个opengles引擎？

**Comment by reaper12** [comment]
是的，VR这部分的实现有点和您的类似

**Comment by reaper12** [comment]
新版本底部扭曲得有点明显，我还是换回上一个版本先

**Comment by jksfood** [comment]
大侠，Pinch手势控制缩放这个有没有思路？我想自己先实现下试试，是通过GLSurferview来处理的吗？主要是怎么识别到缩放的手势？

**Comment by ashqal** [comment]
![image](https://cloud.githubusercontent.com/assets/5126517/15108590/4ff68dca-1609-11e6-95ac-9a564a457b8c.png)
fixed!
