### ISSUE TITLE
switchInteractiveMode(Activity activity, int mode)使用有问题

### ISSUE THREAD

**Issue by reaper12** [ashqal/MD360Player4Android#61]
默认状态是INTERACTIVE_MODE_MOTION，然后使用switchInteractiveMode(Activity activity, int mode)的方式切换为INTERACTIVE_MODE_TOUCH模式，接着再用这个方法切换回INTERACTIVE_MODE_MOTION的话 陀螺仪失效。

**Comment by ashqal** [comment]
我试试

**Comment by ashqal** [comment]
Thanks a lot! 
Fixed!

``` java
compile 'com.github.ashqal:MD360Player4Android:53248700d6'
```
