### ISSUE TITLE
video; pause,play and error!

### ISSUE THREAD

**Issue by yunussahinio** [ashqal/MD360Player4Android#62]
Problem;
![md360-playpause-problem](https://cloud.githubusercontent.com/assets/16646439/16269746/3a1667e0-389c-11e6-9642-cc29d9ba66b4.jpg)

mySolution;
![md360-playpause-solution](https://cloud.githubusercontent.com/assets/16646439/16269747/3a35383c-389c-11e6-9344-87ed82afecc4.jpg)

but.. why?

**Comment by ashqal** [comment]
How to reproduce this crash?
1.pause video
2.play video?

**Comment by yunussahinio** [comment]
sory my english so bad :)
answer:
`3.pause before, play after, and error`

   code style:

```
  if(videoplayer.isPlaying)
      step 1: (button click)onPause // No problem video paused
      step 2: (button click)onResume // and error.. 

```

VideoPlayerActivity:

```
...
...
        buttonOynatDuraklat.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                if (mMediaPlayerWrapper.getPlayer().isPlaying()) {
                    onPause();
                    buttonOynatDuraklat.setImageResource(R.mipmap.oynat);
                } else {
                    onResume();
                    buttonOynatDuraklat.setImageResource(R.mipmap.duraklat);
                }
            }
        });
...
...
```

**Comment by ashqal** [comment]
You should use `mMediaPlayerWrapper#onPause` and  `mMediaPlayerWrapper#onResume`
For example,

``` java
findViewById(R.id.button_pause).setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        mMediaPlayerWrapper.onPause();
    }
});

findViewById(R.id.button_play).setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        mMediaPlayerWrapper.onResume();
    }
});
```

**Comment by yunussahinio** [comment]
whoa.. thanks worked. (why don't i think that)
mysolution( `// mVRLibrary.onPause(this); //mySolution  add this:"//"` ) created other errors..
e.g:
`back button and same error`

 thanks so much.

**Comment by ashqal** [comment]
Good luck!
