### ISSUE TITLE
A problem accured when i tried to play a .mkv format video.

### ISSUE THREAD

**Issue by slashwon** [ashqal/MD360Player4Android#63]
The log shows failed to open input . So it seems that ijkplayer does not support .mkv  . Do you have any  idea to fix the problem ? The ijkplayer and vitamio are both based on ffmpeg , how does the difference happens in format support ?
Besides , when i tried to play some high quality .mp4 video, the player didn't work well and the frame isn't consistent .
I really appreciate the project you wrote . It helped me a  lot in my vr project . Thank you .

**Comment by ashqal** [comment]
Please move to https://github.com/Bilibili/ijkplayer/issues/1024
May help!

**Comment by slashwon** [comment]
It works.But when playing video of large size it will slow down ,the video and the audio may be not synchronouz . I think the ijkplayer has so much to learn . Thanks again !

**Comment by ashqal** [comment]
Glad  to hear that. I will close it.
