### ISSUE TITLE
I just don't have any idea of what these params mean ;

### ISSUE THREAD

**Issue by slashwon** [ashqal/MD360Player4Android#65]
Hi it's me again . In your MediaPlayerWrapper.class the code like this:
player.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec",
                    1);

I don't really know what the params actually mean , how can I find them in the ijkplayer library ,and how can i modify them to improve my project . Hope for your answer!
THANKS!

**Comment by ashqal** [comment]
Sorry, please try to find more information on https://github.com/Bilibili/ijkplayer
