### ISSUE TITLE
How could this app play stereo image?

### ISSUE THREAD

**Issue by ZhengzhongSun** [ashqal/MD360Player4Android#7]
I'm trying to modify this app to play stereo image. In my idea, two view should play 2 images which are capture by 2 cameras. 
What's the better way to implement this function based on your project? Could you give some advice?
Thank you!

**Comment by ashqal** [comment]
For now, this library only render the processed image .
e.g. ![texture](https://cloud.githubusercontent.com/assets/5126517/14597926/6cc36078-0582-11e6-879f-132a95b885b4.jpg)

**Comment by ZhengzhongSun** [comment]
I mean I'm trying to play a top-bottom panorama image, which I can see 2 images in each eye.
![resonance- a jump vr video_20160418163209](https://cloud.githubusercontent.com/assets/13618800/14598078/2d26e39e-0583-11e6-941f-4c4fe81063d9.JPG)
I will implement it just by modifying the shader?

**Comment by ashqal** [comment]
Image Only?

**Comment by ZhengzhongSun** [comment]
For now, I just want to process pictures. After that, I will process videos.

**Comment by ashqal** [comment]
It's so strange. Because it is a 360 degree image, the only difference between two eye is visual scope. Why not moving the camera instead of providing two same image?

Anyway, It seems modifying the shader is the best choice but I don't know how to crop the texture in shader. Another hack way is modifying the .obj file like this.
![image](https://cloud.githubusercontent.com/assets/5126517/14599724/99467dfc-058b-11e6-8cf1-a567682cf758.png)

**Comment by ZhengzhongSun** [comment]
Top and bottom images are 2 different images with disparities, they are not the same. In my situation, I don't need to set 2 eyes with some distance, eyes are in the same place.
I don't understand your hack way. Why there are 4 sphere?

**Comment by ZhengzhongSun** [comment]
I have another question. If  i want to process my rendered images with shader and show it. I know unity has RenderTexture to implement. How to implement it with opengl es in andorid?

**Comment by ashqal** [comment]
[MD360BitmapTexture](https://github.com/ashqal/MD360Player4Android/blob/master/vrlib/src/main/java/com/asha/vrlib/texture/MD360BitmapTexture.java) 

``` java
private void textureInThread(int textureId, Bitmap bitmap) {
    notNull(bitmap,"bitmap can't be null!");

    if (isEmpty(textureId)) return;

    // Bind to the texture in OpenGL
    GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, textureId);

    // Set filtering
    GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D, GLES20.GL_TEXTURE_MIN_FILTER, GLES20.GL_NEAREST);
    GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D, GLES20.GL_TEXTURE_MAG_FILTER, GLES20.GL_NEAREST);

    // Load the bitmap into the bound texture.
    GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, bitmap, 0);
}
```

**Comment by ZhengzhongSun** [comment]
These codes can't postprocess the rendered image.

**Comment by ZhengzhongSun** [comment]
I have a question. The sphere is consist of a lot of triangles. How did you attach the texture image to the sphere? Thank you!

**Comment by ashqal** [comment]
[Texture Coordinate](http://stackoverflow.com/questions/5532595/how-do-opengl-texture-coordinates-work)

**Comment by ashqal** [comment]
will implement soon.
