### ISSUE TITLE
鱼眼镜头（畸变校正）

### ISSUE THREAD

**Issue by zhanwenxu2015** [ashqal/MD360Player4Android#70]
你好，请问畸变校正这部分是否有涉及，鱼眼镜头这样的效果能否给个实现思路。

**Comment by ashqal** [comment]
1.没有做畸变校正
2.鱼眼的话可以试一下创建DirectorFactory的时候`setEyeZ()`,范围可以试一下10-18,说不定是你想要的效果

**Comment by ashqal** [comment]
9f0c385b6db64afe3fad2064cbedd65a11cbdf59
