### ISSUE TITLE
INTERACTIVE_MODE_MOTION OPPO R9 运行DEMO 会出现黑屏

### ISSUE THREAD

**Issue by xiesx123** [ashqal/MD360Player4Android#72]

**Comment by ashqal** [comment]
你是怎么播放的？点的asVideo?

**Comment by 136305973** [comment]
对的，直接在Demo基础上，asVideo 测试播放地址如下：
http://cache.utovr.com/201508270528174780.m3u8
切换MODE_MOTION模式，会出现黑屏！
老版本，没该问题！

**Comment by ashqal** [comment]
![image](https://cloud.githubusercontent.com/assets/5126517/16590625/eb8af608-430a-11e6-98b7-609557b8dbe7.png)
Nexus 5x无法复现，麻烦试一下其他机型

**Comment by ashqal** [comment]
![image](https://cloud.githubusercontent.com/assets/5126517/16590949/3e33d4aa-430c-11e6-8042-134e36041394.png)
魅蓝note也无法复现，你的调用方式是否存在问题？

**Comment by 136305973** [comment]
E/SensorManager: RegisterListener Rotation Vector Sensor type:11 delay:20000us by com.asha.vrlib.strategy.interactive.MotionStrategy

这些是debug打印的信息

**Comment by mamiaokui** [comment]
魅族mx重现了。是传感器给了一些NA值导致的。carboard M模式下没有问题。
