### ISSUE TITLE
Cardboard support

### ISSUE THREAD

**Issue by 155martinmoreno** [ashqal/MD360Player4Android#74]
Do you guys provide Cardboard support? can't find it in the docs

**Comment by leo-plus** [comment]
Did you notice in the video player demo, on the left top corner, there is a button named "normal", click it, it can trigger the glass mode. Then... there's no docs. Read the fucking code.

**Comment by 155martinmoreno** [comment]
Idiotic insults aside, I was looking to this image:

![image](https://cloud.githubusercontent.com/assets/8753819/16716403/17229846-46d2-11e6-8060-4dd01cdd02a3.png)

and wondering if the "glass" mode is analog to the cardboard (projection etc) because I'm new to the subject.

**Comment by ashqal** [comment]
9f0c385b6db64afe3fad2064cbedd65a11cbdf59
