### ISSUE TITLE
Consider use GLTextureView or TextureView.

### ISSUE THREAD

**Issue by leo-plus** [ashqal/MD360Player4Android#75]
GLTextureView: [https://github.com/romannurik/muzei/blob/master/main/src/main/java/com/google/android/apps/muzei/render/GLTextureView.java](url)

**Comment by ashqal** [comment]
awesome, thx very much! Will impl soon.

**Comment by ashqal** [comment]
It seems that setPreserveEGLContextOnPause is not supported of the code above.

**Comment by leo-plus** [comment]
Sorry for my shallow description for GLTextureView. You can create a GLTextureView by yourself.

Maybe is link could solve your problem:  [http://stackoverflow.com/questions/12061419/converting-from-glsurfaceview-%20*%20to-textureview-via-gltextureview](url)
I mean you can add this API(setPreserveEGLContextOnPause) by yourself.

In our project, we have this API(setPreserveEGLContextOnPause), and it's worked fine.

**Comment by ashqal** [comment]
I have implement it in the MD360 project.
https://github.com/ashqal/MD360Player4Android/blob/09d413f33ade86a1b682914350801e388395b36c/vrlib/src/main/java/com/asha/vrlib/MDGLScreenWrapper.java

But, the function of `setPreserveEGLContextOnPause` is not worked correctlly, do you have any idea of fixing it?

**Comment by ashqal** [comment]
I have made a mistake, it worked fine!
