### ISSUE TITLE
Which function is similar to timeDidChange (iOS) in android?

### ISSUE THREAD

**Issue by ghost** [ashqal/MD360Player4Android#78]

**Comment by ashqal** [comment]
You can use handle (post delay) to update the slider bar.

**Comment by ghost** [comment]
I am using handle to update slider bar but  while manually changing slide bar then video is playing from starting.  
and log is giving this 
07-27 14:29:40.435 3933-3933/com.asha.md360player4android D/IJKMEDIA: IjkMediaPlayer_seekTo
07-27 14:29:40.435 3933-3933/com.asha.md360player4android D/IJKMEDIA: ijkmp_seek_to(22000)
07-27 14:29:40.435 3933-3933/com.asha.md360player4android D/IJKMEDIA: ijkmp_seek_to(22000)=0
07-27 14:29:40.435 3933-14314/com.asha.md360player4android D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_SEEK
07-27 14:29:40.947 3933-14314/com.asha.md360player4android D/IJKMEDIA: FFP_MSG_BUFFERING_START:
07-27 14:29:40.954 3933-14337/com.asha.md360player4android D/IJKMEDIA: SDL_AMediaCodecJava_flush
07-27 14:29:40.954 3933-14314/com.asha.md360player4android D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
07-27 14:29:40.954 3933-14314/com.asha.md360player4android D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:

**So can you please tell me How can I implement forward and backward functionality using seekTo?**

**Comment by matejvida** [comment]
Are you feeding the right data to the seekTo? It looks like you are getting a 0 value from the slider when changing it.

**Comment by ghost** [comment]
yes i am feeding right value in form of  milliseconds in seekTo. 

snippet is here
@Override
            public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
                if (mMediaPlayerWrapper != null && fromUser) {
                    Log.i("seek", "seek position " + progress \* 1000);
                    mMediaPlayerWrapper.getPlayer().seekTo(progress \* 1000);
                    seekBar().setProgress((int) (mMediaPlayerWrapper.getPlayer().getCurrentPosition() / 1000));
                }
 }

also tried this one also

@Override
            public void onStopTrackingTouch(SeekBar seekBar) {
                if (mMediaPlayerWrapper != null) {
                    uiThreadRunning = true;
                    Log.i("seek", "seek position " + seekBar.getProgress());
                    mMediaPlayerWrapper.getPlayer().seekTo(seekBar.getProgress());
                    seekBar().setProgress((int) (mMediaPlayerWrapper.getPlayer().getCurrentPosition()));
                }
            }
