### ISSUE TITLE
功能讨论(interactive improvement)

### ISSUE THREAD

**Issue by reaper12** [ashqal/MD360Player4Android#8]
hello大神，有个功能想和您讨论下。
一般情况下，视频播放后我们才会手机放到VR设备里观看，这样的话就会出现已经播放了一段，而且在观看途中也无法暂停，只有把手机从设备拿出来之后才能进行视频的暂停。能不能设置一个这样的功能：当头往下低看底部的时候进入某个区域范围的时候可以触发一个事件，我们可以在事件里进行播放和暂停的操作，退出这个区域范围的时候还可以触发一个事件，方便取消操作。有点类似于UtoVR的功能。

**Comment by ashqal** [comment]
好主意，目前有哪些流行的交互方案？
比如直视某个区域2秒以上抛出事件？

**Comment by ZhengzhongSun** [comment]
Jaunt VR has a good UI in this aspect.

**Comment by reaper12** [comment]
对于视频播放来说  能操作的就是播放状态的改变，这个是操作最多的，如果在平视的时候触发事件，这样在观看视频的时候体验会不好，唯有向底部或者顶部看的时候触发要好一点，应该不会有人长时间的抬头看或者低头看吧

**Comment by reaper12** [comment]
可以把陀螺仪的changed事件回调出来自己做处理

**Comment by ashqal** [comment]
``` java
 compile 'com.github.ashqal:MD360Player4Android:2.0.0.beta'
```
