### ISSUE TITLE
MODE MOTION - MD360Director NOT WORK

### ISSUE THREAD

**Issue by misaelemc** [ashqal/MD360Player4Android#80]
Hello, very good job with this library. But I have come across a problem of positioning the camera, when I'm in motion mode. MD360Director not work when you want to apply the motion mode. in my case, I need to position the camera at the center point of the frame.

**Comment by ashqal** [comment]
Sorry, I can't understand..

**Comment by misaelemc** [comment]
One question, when you create a director, you can move the  camera around of the sphere in degree. right? if you apply one direction, where you want to orientation the camera in whatever point of the video, the logic is that video begin in that orientation. when you play a video you can apply an md360director and when the sensor starts, remove the original orientation and sends the camera to the north. I think the video should start in the orientation to be set in the md360director settings, and from there move the sensor. 

What do you thing?

**Comment by ashqal** [comment]
MD360Director Customize (since 1.2.0)

``` java
@Override
protected MDVRLibrary createVRLibrary() {
    return MDVRLibrary.with(this)
            ...
            .directorFactory(new DirectorFactory()) 
            ...
            .build(R.id.surface_view);
}

private static class DirectorFactory extends MD360DirectorFactory{
    @Override
    public MD360Director createDirector(int index) {
        switch (index){
            // setAngle: angle to rotate in degrees
            case 1:   return MD360Director.builder().setAngle(20).setEyeX(-2.0f).setLookX(-2.0f).build();
            default:  return MD360Director.builder().setAngle(20).build();
        }
    }
}
```

Is that what you want?
