### ISSUE TITLE
請問該怎麼切換軟、硬解?

### ISSUE THREAD

**Issue by katelin013** [ashqal/MD360Player4Android#81]
請問初始化player之後, 該怎麼使用Button 之類的方式切換軟硬解碼?

直接對player設定player.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 0 );
發現似乎沒有用,
有試過重新new一個新的player , 但是發現只有聲音影像停在原本的地方不會動
thanks

**Comment by ashqal** [comment]
new的话需要重新设置下surface

**Comment by ashqal** [comment]
解决了吗？
