### ISSUE TITLE
【BUG】切换视频过后MODE_MOTION不起作用了

### ISSUE THREAD

**Issue by scar1et** [ashqal/MD360Player4Android#83]
使用下面方法在某页面初始化MDVRLibrary，然后播放第一个视频的时候没有问题，切换视频的时候再次调用下面的方法初始化MDVRLibrary，播放视频的时候MODE_MOTION就不起作用了，MODE_TOUCH是正常的。
    private void initMDVRLibrary(boolean isVRVideo) {
        rlVideoPlayer.removeAllViews();
        GLSurfaceView svVideoPlayer = new GLSurfaceView(context);
        svVideoPlayer.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT));
        rlVideoPlayer.addView(svVideoPlayer);
        mdvrLibrary = MDVRLibrary.with((BaseActivity) context)
                .projectionMode(isVRVideo ? MDVRLibrary.PROJECTION_MODE_SPHERE : MDVRLibrary.PROJECTION_MODE_PLANE_FIT)
                .displayMode(MDVRLibrary.DISPLAY_MODE_NORMAL)
                .interactiveMode(MDVRLibrary.INTERACTIVE_MODE_TOUCH)
                .pinchEnabled(true)
                .asVideo(new MDVRLibrary.IOnSurfaceReadyCallback() {
                    @Override
                    public void onSurfaceReady(Surface surface) {
                        mediaPlayer.setSurface(surface);
                    }
                })
                .gesture(new MDVRLibrary.IGestureListener() {
                    @Override
                    public void onClick(MotionEvent e) {
                        if (rlVideoController != null) {
                            if (rlVideoController.getVisibility() == View.VISIBLE) {
                                rlVideoController.setVisibility(View.GONE);
                                cancelTimer();
                            } else {
                                rlVideoController.setVisibility(View.VISIBLE);
                                startTimer();
                            }
                        }
                    }
                })
                .directorFactory(new MD360DirectorFactory() {
                    @Override
                    public MD360Director createDirector(int index) {
                        return MD360Director.builder().setAngleX(-90F).build();
                    }
                })
                .build(svVideoPlayer);
    }

**Comment by ashqal** [comment]
不正常的时候切到touch，再切回motion正常吗

**Comment by scar1et** [comment]
不正常，切到touch是正常的，回来motion就不正常了

**Comment by scar1et** [comment]
这个是必现问题，出现问题之后，Motion不正常，M&T模式只能Touch的时候有反应，您可以切换用上面代码试试。
或者您能提供别的视频切换方案吗？

**Comment by ashqal** [comment]
你把你的代码整理成demo发我邮箱吧，我帮你看看

**Comment by scar1et** [comment]
谢谢大神热心解答，我已经解决这个问题了，重新初始化mdvrLibrary并切换了url之后调用一下onResume就好了，之后motion就可以用了。

ps：Demo刚刚写好，准备发之前测试一波，重现了问题，然后不小心按到了home键，回来就好了，之后想到调用一下onResume看看，果然可以了。这种意外之喜真是触不及防2333333，再次感谢您让我写这个Demo！

**Comment by ashqal** [comment]
赞
