### ISSUE TITLE
最新版本的如何看视频啊

### ISSUE THREAD

**Issue by yhb612** [ashqal/MD360Player4Android#85]
选了MP4之后下面三个按钮都无法看视频

**Comment by ashqal** [comment]
如果是视频应该选择asVideo，logcat日志报什么？可以确认MP4在对应路径存在吗？

**Comment by yhb612** [comment]
查了下没有mp4 要去哪里下载

**Comment by yhb612** [comment]
08-08 16:49:22.735  24378-24737/com.asha.md360player4android E/IJKMEDIA﹕ file:///mnt/sdcard/vr/videos_s_4.mp4: No such file or directory
08-08 16:49:22.735  24378-24737/com.asha.md360player4android I/IJKMEDIA﹕ SDL_JNI_DetachThreadEnv: [24737]
08-08 16:49:22.735  24378-24735/com.asha.md360player4android D/IJKMEDIA﹕ FFP_MSG_ERROR: 0
08-08 16:49:22.790  24378-24378/com.asha.md360player4android E/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Error (-10000,0)
08-08 16:49:22.812  24378-24734/com.asha.md360player4android D/IJKMEDIA﹕ IjkMediaPlayer_setVideoSurface
08-08 16:49:22.812  24378-24734/com.asha.md360player4android D/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0xe12bb920)
08-08 16:49:22.812  24378-24734/com.asha.md360player4android D/IJKMEDIA﹕ ffpipeline_set_surface()
08-08 16:49:22.812  24378-24734/com.asha.md360player4android D/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0xe12bb920)=void
08-08 16:49:22.921  24378-24406/com.asha.md360player4android V/RenderScript﹕ Application requested CPU execution
08-08 16:49:22.936  24378-24406/com.asha.md360player4android V/RenderScript﹕ 0xeec15600 Launching thread(s), CPUs 6
08-08 16:49:22.969  24378-24406/com.asha.md360player4android D/OpenGLRenderer﹕ endAllActiveAnimators on 0xf4b9f280 (RippleDrawable) with handle 0xf4b7fbe0

**Comment by ashqal** [comment]
http://120.52.73.48/d8d913s460fub.cloudfront.net/krpanocloud/video/airpano/video-1920x960a.mp4

**Comment by yhb612** [comment]
服务器不好使了吧？
