### ISSUE TITLE
Show  Stereo image

### ISSUE THREAD

**Issue by sinaone1** [ashqal/MD360Player4Android#88]
Dear ashqal
Your library is fantastic.
But could i show a Stereo Image in this library like this?
![pano0](https://cloud.githubusercontent.com/assets/11288019/17491751/2e42799e-5dbe-11e6-8c6a-d3b0888bb221.jpg)

Or this:
![06-vikingvillage_stereo_thumb](https://cloud.githubusercontent.com/assets/11288019/17491833/7d33d6ba-5dbe-11e6-9a7f-18b27c5e706d.jpg)

Thank you.

**Comment by ashqal** [comment]
``` java
// projection mode in MDVRLibrary.java
public static final int PROJECTION_MODE_SPHERE = 201;
public static final int PROJECTION_MODE_DOME180 = 202;
public static final int PROJECTION_MODE_DOME230 = 203;
public static final int PROJECTION_MODE_DOME180_UPPER = 204;
public static final int PROJECTION_MODE_DOME230_UPPER = 205;
public static final int PROJECTION_MODE_STEREO_SPHERE = 206;
public static final int PROJECTION_MODE_PLANE_FIT = 207;
public static final int PROJECTION_MODE_PLANE_CROP = 208;
public static final int PROJECTION_MODE_PLANE_FULL = 209;

// You should call MDVRLibrary#onTextureResize(float width, float height)
// If you are using DOME projection and PLANE projection.

@Override
protected MDVRLibrary createVRLibrary() {
    return MDVRLibrary.with(this)
            ...
            .projectionMode(MDVRLibrary.PROJECTION_MODE_STEREO_SPHERE)
            ...
            .build(R.id.surface_view);
}

// switch in runtime
// MDVRLibrary.PROJECTION_MODE_STEREO_SPHERE
MDVRLibrary#switchProjectionMode(Activity activity, int mode)
```

**Comment by sinaone1** [comment]
First thank you for your response.
But this is a stereo image and actually you must see left image into left sphere and right image into right sphere, because with stereo image you could see a 3d image. 
So how could i show a stereo image into this library? 
Thank you.

**Comment by ashqal** [comment]
![image](https://cloud.githubusercontent.com/assets/5126517/17501882/8e187416-5e15-11e6-8726-8674006147b9.png)
![image](https://cloud.githubusercontent.com/assets/5126517/17501892/a52e1ef8-5e15-11e6-8450-174b5ba7104a.png)

``` java
MDVRLibrary.PROJECTION_MODE_STEREO_SPHERE
```

IT IS just what you want.

**Comment by sinaone1** [comment]
Thank you very much :)
