### ISSUE TITLE
How could i add a hotspot in onClick event of gesture

### ISSUE THREAD

**Issue by sinaone1** [ashqal/MD360Player4Android#92]
Dear Ashqal
I would like add a hotspot when user click on a position of my bitmap.
I guess i have to use onClick gesture event.
But how could i get clicked position in onClick gesture for add a hostspot?
Thank you.

**Comment by ashqal** [comment]
The point you clicked is a 2d(x,y) position, and can not convert to a 3d(x,y,z) position, the only info that I can provide is the position of the camera and the vector which direction is point to clicked position, called `MDRay`.

**Comment by sinaone1** [comment]
It's really good for me.
So could you write an example code that how can i add a hostspot in direction of point to clicked position?
Thank you.

**Comment by ashqal** [comment]
Pushed.

**Comment by ashqal** [comment]
``` java
@Override
protected MDVRLibrary createVRLibrary() {
    return MDVRLibrary.with(this)
            ...
            .listenTouchPick(new MDVRLibrary.ITouchPickListener() {
                @Override
                public void onHotspotHit(IMDHotspot hitHotspot, MDRay ray) {
                    Log.d(TAG,"Ray:" + ray + ", hitHotspot:" + hitHotspot);
                }
            })
            .build(R.id.gl_view);
}
```

**Comment by sinaone1** [comment]
Thank you very much

**Comment by mudin3i** [comment]
hello,

Can you share your code?
I cannot figure it out.
I got the ray's x,y,z and I set hotspot position, but it is weird, it is not what I need.
Please help!

Mudin

**Comment by mudin3i** [comment]
I successfully made it work, but not sure if it is optimal way
on HotspotHit:

```
public void onHotspotHit(IMDHotspot hitHotspot, MDRay ray) {
    float x = ray.getDir().getX();
    float y = ray.getDir().getY();
    float z = ray.getDir().getZ();

    float atv = (float) Math.toDegrees(Math.atan2(y,Math.sqrt(x*x+z*z)));
    float ath = - (float) Math.toDegrees(Math.atan2(x,z));
    addHotspot(ath, atv);
}
```
and in addHotspot(ath,atv) function:

```
float y = (float) (-SPHERE_RADIUS * Math.sin(Math.toRadians(atv)));
float r = (float) (-SPHERE_RADIUS * Math.cos(Math.toRadians(atv)));
float x = (float) (r * Math.sin(Math.toRadians(-ath)));
float z = (float) (r * Math.cos(Math.toRadians(-ath)));
position.setX(x).setY(y).setZ(z).setPitch(-ath).setYaw(-atv);
```

And I found that setYaw and Pitch has some issue:
in MDPosition.java I rotate pitch first and then yaw, it is working for me 
```
Matrix.translateM(mCurrentRotation, 0, getX(), getY(), getZ());
Matrix.rotateM(mCurrentRotation, 0, getPitch(), 0.0f, 1.0f, 0.0f);
Matrix.rotateM(mCurrentRotation, 0, getYaw(), 1.0f, 0.0f, 0.0f);
Matrix.rotateM(mCurrentRotation, 0, getRoll(), 0.0f, 0.0f, 1.0f);
```
