### ISSUE TITLE
Show Horizontal Stereo Camera Image 

### ISSUE THREAD

**Issue by sinaone1** [ashqal/MD360Player4Android#94]
Hello ashqal.
My Stereo Camera images are Horizontally like this 
![stereo camera](https://cloud.githubusercontent.com/assets/11288019/17615666/fa5caf4a-6084-11e6-8ff5-dc8cb9d173dc.jpg)
I set projectionMode to MDVRLibrary.PROJECTION_MODE_STEREO_SPHERE.
But it work fine with vertically Stereo Camera Images.
How can i show Horizontally Stereo Camera images?
Thank you.

**Comment by ashqal** [comment]
``` java
 MDVRLibrary.PROJECTION_MODE_STEREO_SPHERE_HORIZONTAL
```

**Comment by sinaone1** [comment]
Thank you very much.
