### ISSUE TITLE
motion和touch问题

### ISSUE THREAD

**Issue by forever1985** [ashqal/MD360Player4Android#95]
hi，
   在新版本中使用的时候，当使用motion和touch同时的生效的模式时，怎么上下滑动不行呢？只能使用左右滑动

**Comment by liuyinchang** [comment]
hi,
我也想知道这个问题怎么解决，下一版本会考虑解决这个问题吗？谢谢

**Comment by b95505017** [comment]
Same issue with #71 ?

**Comment by ashqal** [comment]
@b95505017 Yes.

**Comment by duzzi** [comment]
有大神解决了这个问题么？
我觉得大概是需要修改MD360Director中 shot方法中的一些步骤，但实在是看不大懂，不知道如何解决。

**Comment by Frosch** [comment]
Any updates on this?
I fiddled around a bit, but currently without luck... I'll just explain my idea, maybe someone finds something useful in there :)

I altered `MD360Director.updateViewMatrix()` to use the current orientation for rotation on x and z.
_The idea:_ based on the y-rotation (from the sensor-matrix), we need to rotate on x-axis, z-axis or both. E.g. we face directly into "x-direction", then we need to rotate on the z-axis.

So I retrieved the rotation on the y-axis with
`SensorManager.getAngleChange(angles, mSensorMatrix, mCurrentRotation);`
where `angles` is a float-array with 3 elements. The last one is the needed y-rotation in rad.
I then used this value to calculate "rotation-values" for z and x: 
- 0° and 180° meaning rotation on x
- 90° and 270° meaning rotation on z

This works kinda fine when you are near those "ideal" angles. However, e.g. for 45° the result is "half the rotation on x and the other on z". _Sounds good, looks horrible_.

**Comment by liuyinchang** [comment]
MD360Director.updateViewMatrix() 我改变Matrix.rotateM(mCurrentRotation, 0, -mDeltaY, 1.0f, 0.0f, 0.0f)为Matrix.rotateM(mCurrentRotation, 0, -mDeltaY, 0.1f, 0.0f, 0.2f)只在motion和touch同时的生效模式下打开director.setDeltaY(director.getDeltaY() + distanceY / sDensity \* sDamping);可以实现上下滑动，但是感觉有点问题，应该是涉及到旋转矩阵方面的东西

**Comment by duzzi** [comment]
暂时算是解决了。
touch ：Matrix.rotateM(mCurrentRotation, 0, -mDeltaY, 1.0f, 0.0f, 0.0f);
touch&motion ：Matrix.rotateM(mCurrentRotation, 0, -mDeltaY, 0.0f, 0.0f, 1.0f);
原理还是不是很清楚，求大神解释下。

**Comment by joimxjtuse** [comment]
这个问题我也遇到了，并解决了，把
MotionWithTouchStrategy类的handleDrag（）那段注释的代码打开：
director.setDeltaY(director.getDeltaY() - distanceY / sDensity * sDamping);
就好了。查看了提交日志， 比较费解这段为啥注释掉~

**Comment by Frosch** [comment]
This rather lengthy codeblock inside `MD360Director.updateViewMatrix()` lets you look up and down for most of the sphere. There still is a strange "rotation-point" at around 2.6deg rad where the video rotates around the view-axis. I can't seem to figure out where the problem is, but maybe someone gets inspired by this ;)

``` java
[...]
// get sensor's rotation on y-axis 
float[] angles = new float[3];
SensorManager.getAngleChange(angles, mSensorMatrix, mViewMatrix);
float yAngle = Math.abs(angles[2]);

// we're looking at the quadrants
float rotY = (yAngle > (Math.PI/2)) ? (float) (yAngle - Math.PI) : yAngle;
float rotQuot = (float) Math.abs(rotY / (Math.PI/2));

// without any movement, we're looking at Z
float rotXQuot = 1 - rotQuot;
float rotZQuot = rotQuot;
Matrix.rotateM(mCurrentRotation, 0, -mDeltaY, rotXQuot, 0.0f, rotZQuot);
[...]
```

**Comment by ashqal** [comment]
@Frosch Thanks a lot. I will open a new issue to trace the problem according to your idea.

**Comment by ashqal** [comment]
753a6c03078d81bd23644b42c5e3bcc7e6f182f4
2d025f5dc4106f379f4f8c36289dde77e44c5ffe

**Comment by ashqal** [comment]
753a6c03078d81bd23644b42c5e3bcc7e6f182f4
2d025f5dc4106f379f4f8c36289dde77e44c5ffe

**Comment by b95505017** [comment]
Will a new beta release?

**Comment by ashqal** [comment]
@b95505017 Yes. The 2.1.0 version is released.
