### ISSUE TITLE
VR來源不是2:1, 會造成全景有點變形

### ISSUE THREAD

**Issue by MikeChangFN** [ashqal/MD360Player4Android#96]
你好，目前我的影片來源不是2:1，他的screen size會是1280*960，造成轉出來的全景有些變形。
請問我該如何處理呢，才可以解決變形問題。
如果影像來源上下有黑邊，我能夠在那邊處理將黑邊移除，來保證來源的比例為2:1？
感謝～

**Comment by ashqal** [comment]
不是2：1没有关系，后面会根据回调计算新的比例，变形不是这个问题导致的吧？
你说的变形可以截个图吗？

**Comment by MikeChangFN** [comment]
邊緣的部分會有點變形~~~

![image](https://cloud.githubusercontent.com/assets/11451498/17722723/f619188e-6466-11e6-9a89-6e5ca724ec00.png)

![image](https://cloud.githubusercontent.com/assets/11451498/17722734/0b6a958c-6467-11e6-9420-af7b8d6c708a.png)

**Comment by ashqal** [comment]
![image](https://cloud.githubusercontent.com/assets/5126517/17722903/537756de-6468-11e6-8c86-b772ec79755f.png)

你的片源是这种吗？这种得用DOME来播放
