### ISSUE TITLE
can not play rtsp?

### ISSUE THREAD

**Issue by asata** [ashqal/MD360Player4Android#97]
> 08-16 16:41:13.903 26451-29036/com.asha.md360player4android W/IJKMEDIA: remove 'timeout' option for rtmp.
> 08-16 16:41:13.904 26451-29036/com.asha.md360player4android E/IJKMEDIA: rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp: Protocol not found
> 08-16 16:41:13.904 26451-29034/com.asha.md360player4android D/IJKMEDIA: FFP_MSG_ERROR: 0
> 08-16 16:41:13.904 26451-29036/com.asha.md360player4android I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [29036]
> 08-16 16:41:14.020 26451-26451/com.asha.md360player4android E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
> 08-16 16:41:14.042 26451-29033/com.asha.md360player4android D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
> 08-16 16:41:14.042 26451-29033/com.asha.md360player4android D/IJKMEDIA: ijkmp_set_android_surface(surface=0x9f2bf350)
> 08-16 16:41:14.042 26451-29033/com.asha.md360player4android D/IJKMEDIA: ffpipeline_set_surface()
> 08-16 16:41:14.042 26451-29033/com.asha.md360player4android D/IJKMEDIA: ijkmp_set_android_surface(surface=0x9f2bf350)=void
> 08-16 16:41:14.176 26451-26489/com.asha.md360player4android D/OpenGLRenderer: endAllStagingAnimators on 0x9eaf1700 (RippleDrawable) with handle 0x9f6f9bc0

still can not play rtsp.

what else should I do?

**Comment by ashqal** [comment]
[jniLibs.zip](https://github.com/ashqal/MD360Player4Android/files/420249/jniLibs.zip)
`STEP1 COPY THE jniLibs TO YOUR PROJECT`
![image](https://cloud.githubusercontent.com/assets/5126517/17699209/0fd53dd6-63f2-11e6-8e7b-b21e396d9a3e.png)

`STEP2 DELETE THE IMPORT OF ijkplayer-armv7a`
![image](https://cloud.githubusercontent.com/assets/5126517/17699269/56c3ee4a-63f2-11e6-99c2-2a927571a228.png)
