### ISSUE TITLE
横竖屏切换crash

### ISSUE THREAD

**Issue by ajaxzhang** [ashqal/MD360Player4Android#98]
横竖屏切换crash，做保护后 ， 出现eglsurface invaild

希望解决，谢谢

**Comment by ajaxzhang** [comment]
切换屏幕调用的setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)
之前0.9版本是没问题的。

**Comment by ashqal** [comment]
可以在demo的基础上写个必复现的例子吗？

**Comment by ajaxzhang** [comment]
demo没复现， 我使用问题，多谢
