### ISSUE TITLE
Motion Sensor not working on some devices

### ISSUE THREAD

**Issue by sinaone1** [ashqal/MD360Player4Android#99]
Hello ashqal.
I have problem with some devices.
For example Samsung A7 have motion sensor but motion sensor not working with this application.
Where is the problem?
Thank you

**Comment by obraz** [comment]
Same situation on Samsung A3

**Comment by matejvida** [comment]
Is there a way that we can detect a malfunction in the sensor data, so we can turn off the motion sensors and use just use the touch gestures?

**Comment by ashqal** [comment]
@matejvida Yes,
https://github.com/ashqal/MD360Player4Android/wiki/Advanced-Usage#feature-not-support-callback

**Comment by sinaone1** [comment]
Thank you very much.And I would really thank you if add Horizontal Stereo Camera projection mode to your project.
thank you again.

**Comment by ashqal** [comment]
Please try 

``` java
MDVRLibrary.INTERACTIVE_MODE_CARDBORAD_MOTION
```
